src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_Supplier__c</fullName>
        <label>Primary Supplier (Non Behr)</label>
        <picklist>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex (Frazee/Kwal/Color Wheel/Parker)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG (Olympic/Pittsburgh/Porter)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin-Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valspar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <picklist>
            <picklistValues>
                <fullName>Behr In-Store Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behr PPSSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BehrPRO Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Depot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mktg-driven National Event/Trade Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Event/Trade Show</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>Key market segments.</description>
        <inlineHelpText>Segment must be selected. DO NOT select THD Pilot Programs (for internal reporting purposes ONLY).</inlineHelpText>
        <label>Market Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B2B(OEM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exporter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goverment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Painting and Wall Covering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remodeler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THD Pilot Programs</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market_Sub_Segment__c</fullName>
        <description>Sub-segments tied to key markets and contractor categories.</description>
        <inlineHelpText>Must choose one.</inlineHelpText>
        <label>Market Sub Segment</label>
        <picklist>
            <controllingField>Market_Segment__c</controllingField>
            <picklistValues>
                <fullName>New Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repair &amp; Remodel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Construction-Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Construction-Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carryout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>Property Type</label>
        <picklist>
            <controllingField>Market_Sub_Segment__c</controllingField>
            <picklistValues>
                <fullName>Commercial: Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial: Government/Municipality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial: Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial: Hospitality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial: Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial: Office/Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial: Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential: Multi-family Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential: Single Family Homes</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Direct_Onboarding__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Onboardings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Supplier__c</fullName>
        <label>Current Supplier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <formula>TEXT(Account_Name__r.Market_Segment__c)</formula>
        <label>Market Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Sub_Segment__c</fullName>
        <label>Market Sub Segment</label>
        <picklist>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Direct Onboarding</label>
    <nameField>
        <displayFormat>AO-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Direct_On_Boarding_Attach_Trig_Test.cls
@isTest(SeeAllData=true)
public class Direct_On_Boarding_Attach_Trig_Test {
	static testMethod void testAttachments()
    {
        Test.startTest();
    	//List<Direct_Onboarding__c> dobcs = new List<Direct_Onboarding__c>();
       // dobcs.add(new Direct_Onboarding__c(Name='Test Direct Acct'));
        Account acct = new Account(Name = 'Test Direct Account', Phone = '7145457101',Market_Segment__c = 'Architect',Market_Sub_Segment__c = 'New Contsruction',Property_Type__c = 'Residential: Single Family Homes',Current_Supplier__c = 'Valspar',Lead_Source__c  = 'Behr In-Store Rep' );
        insert acct;
        Direct_Onboarding__c dobc = new Direct_Onboarding__c();
        dobc.Account_Name__c=acct.Id;
        insert dobc;
        Attachment attach=new Attachment();   	
    	attach.Name='Unit Test Attachment';
    	Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    	attach.body=bodyBlob;
        attach.parentId=dobc.id;
        insert attach;
    	
    	List<Attachment> attachments=[select id, name from Attachment where parent.id=:dobc.id];
        System.assertEquals(1, attachments.size());
        
        delete attach;
        List<Attachment> attachmentsdel=[select id, name from Attachment where parent.id=:dobc.id];
        System.assertEquals(0, attachmentsdel.size());
        
        Test.stopTest();
    }
}