src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>Sub-Lead Source</label>
        <picklist>
            <controllingField>Lead_Source__c</controllingField>
            <picklistValues>
                <fullName>Contractor Trade Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THD Pro Blitz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Rep Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DTP Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Magazine Publication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web to Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BehrPro Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PASA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>See Trade Association/Affiliation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store Walk In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Actual_Sales__c.object
<CustomObject>
    <description>New object that will contain header and line items against opportunity and account</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Actual Sales</relationshipLabel>
        <relationshipName>Actual_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Actual Sales</relationshipLabel>
        <relationshipName>Actual_Sales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SAP_Order__c</fullName>
        <description>used for external upsert only.</description>
        <externalId>true</externalId>
        <label>SAP Order</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Actual Sales</label>
    <nameField>
        <label>Record ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actual Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Actual_Sales_Line_Items__c.object
<CustomObject>
    <description>The line items on an order</description>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <label>Line #</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Multiplier__c</fullName>
        <label>Multiplier</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SAP_Order__c</fullName>
        <label>SAP Order</label>
        <referenceTo>Actual_Sales__c</referenceTo>
        <relationshipLabel>Acutal Sales Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>external_id__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Actual Sales Line Item</label>
    <nameField>
        <label>Order Item Combo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actual Sales Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Direct_Onboarding__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to determine the relationship between direct onboarding and Case(credit review)</description>
        <label>Direct Onboarding</label>
        <referenceTo>Direct_Onboarding__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label># Of Printed Copies</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Direct_Onboarding__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Onboardings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Direct Onboarding</label>
    <nameField>
        <displayFormat>AO-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Behr_Rep_Contact__c</fullName>
        <description>Customer would like for a Behr Rep to contact them</description>
        <inlineHelpText>Indicates if the customer would like  a Behr Rep to contact them</inlineHelpText>
        <label>Behr Rep Contact</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Monthly_Paint_Usage__c</fullName>
        <label>Estimated Monthly Paint Usage</label>
        <picklist>
            <picklistValues>
                <fullName>&lt;50 Gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51-124 Gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;125 Gallons</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Over 45 gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;124 Gallons</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <description>Sub lead source</description>
        <label>Sub-Lead Source</label>
        <picklist>
            <controllingField>LeadSource</controllingField>
            <picklistValues>
                <fullName>Contractor Trade Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THD Pro Blitz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Rep Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DTP Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Magazine Publication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web to Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BehrPro Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PASA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>See Trade Association/Affiliation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store Walk In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>Sub-Lead Source</label>
        <picklist>
            <controllingField>LeadSource</controllingField>
            <picklistValues>
                <fullName>Contractor Trade Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THD Pro Blitz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Rep Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DTP Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Magazine Publication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web to Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BehrPro Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PASA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>See Trade Association/Affiliation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store Walk In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity Sales Process</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <recordTypes>
        <fullName>Quote</fullName>
        <active>true</active>
        <label>Quote</label>
    </recordTypes>
</CustomObject>

src/classes/UtilNovaUnitTest.cls
@isTest
public class UtilNovaUnitTest { 
/*
* @Method This method getUser is used to get a User
* @param Method is not having any parameters
* @return User - Method returning instance of User
* @throws exception - Method is not throwing any exception
*/ 
 public static User getUser(){ 
      String aliasString = 'resutset';
     Id sysAdminId = [Select Id from Profile Where Name = 'System Administrator' Limit 1].Id;
     User usr = new User(
     alias = aliasString, 
      email= aliasString+'@accenture.com',
     emailencodingkey='UTF-8',
     lastname='Testing', 
      languagelocalekey='en_US',
     localesidkey='en_US',
     profileid = sysAdminId,
     timezonesidkey='Europe/London',
     username= 'testforbehr@expl.com');
     insert usr;
     return usr;
}

/*
* @Method This method  getAccount is used to get a  Account
* @param Method is not having any parameters
* @return Account - Method returning instance of  Account
* @throws exception - Method is not throwing any exception
*/  
 public static Account getAccount() {
      Account accountSample=new Account();
      accountSample.Name='Test Account';

      return accountSample;
  }

/*
* @Method This method  getActual_Sales_Line_Items__c is used to get a  Actual_Sales_Line_Items__c
* @param Method is not having any parameters
* @return Actual_Sales_Line_Items__c - Method returning instance of  Actual_Sales_Line_Items__c
* @throws exception - Method is not throwing any exception
*/  
 public static Actual_Sales_Line_Items__c getActual_Sales_Line_Items_c() {
      Actual_Sales_Line_Items__c actual_sales_line_itemsSample=new Actual_Sales_Line_Items__c();
      actual_sales_line_itemsSample.Name='Test Actual_Sales_Line_Items__c';

      actual_sales_line_itemsSample.Cost__c=1.00;
      actual_sales_line_itemsSample.Line__c=1.0;
      actual_sales_line_itemsSample.Multiplier__c=1.00;
      actual_sales_line_itemsSample.Quantity__c=1.0;
      Actual_Sales__c sampleActual_Sales_c =getActual_Sales_c();
      insert sampleActual_Sales_c;

      actual_sales_line_itemsSample.SAP_Order__c = sampleActual_Sales_c.Id;
      actual_sales_line_itemsSample.external_id__c='Test Actual_Sales_Li';
      return actual_sales_line_itemsSample;
  }

/*
* @Method This method  getActual_Sales__c is used to get a  Actual_Sales__c
* @param Method is not having any parameters
* @return Actual_Sales__c - Method returning instance of  Actual_Sales__c
* @throws exception - Method is not throwing any exception
*/  
 public static Actual_Sales__c getActual_Sales_c() {
      Actual_Sales__c actual_salesSample=new Actual_Sales__c();
      actual_salesSample.Name='Test Actual_Sales__c';

      Account sampleAccount =getAccount();
      insert sampleAccount;

      actual_salesSample.Account_Name__c = sampleAccount.Id;
      Opportunity sampleOpportunity =getOpportunity();
      insert sampleOpportunity;

      actual_salesSample.Opportunity__c = sampleOpportunity.Id;
      return actual_salesSample;
  }


/*
* @Method This method  getLead is used to get a  Lead
* @param Method is not having any parameters
* @return Lead - Method returning instance of  Lead
* @throws exception - Method is not throwing any exception
*/  
 public static Lead getLead() {
      Lead leadSample=new Lead();
      leadSample.salutation='Mr.';
      leadSample.FirstName='Test LastName1232';
      leadSample.LastName='Test LastName';
      leadSample.Company = 'Accenture';
      leadSample.Email = 'testabc@ghjkl.com';
      leadSample.lastname = 'TestAbcName';
      leadSample.Company = 'ACBe';
      leadSample.Phone = '97889763846454';
      leadSample.Status = 'New';
      leadSample.LeadSource = 'RAM';
      leadSample.Sub_Lead_Source__c = 'Cold Call';
      leadSample.Estimated_Monthly_Paint_Usage__c ='>125 Gallons';
      leadSample.Behr_Rep_Contact__c ='Yes';
      insert leadSample;
      return leadSample;
  }
  

/*
* @Method This method  getCase is used to get a  Case
* @param Method is not having any parameters
* @return Case - Method returning instance of  Case
* @throws exception - Method is not throwing any exception
*/  
 public static Case getCase() {
      Case caseSample=new Case();
      caseSample.SuppliedEmail = 'test@salesforce.com';
      return caseSample;
  }



/*
* @Method This method  getDirect_Onboarding__c is used to get a  Direct_Onboarding__c
* @param Method is not having any parameters
* @return Direct_Onboarding__c - Method returning instance of  Direct_Onboarding__c
* @throws exception - Method is not throwing any exception
*/  
 public static Direct_Onboarding__c getDirect_Onboarding_c() {
      Direct_Onboarding__c direct_onboardingSample=new Direct_Onboarding__c();
      return direct_onboardingSample;
  }


/*
* @Method This method  getOpportunity is used to get a  Opportunity
* @param Method is not having any parameters
* @return Opportunity - Method returning instance of  Opportunity
* @throws exception - Method is not throwing any exception
*/  
 public static Opportunity getOpportunity() {
      Opportunity opportunitySample=new Opportunity();
      opportunitySample.Name='Test Opportunity';

      opportunitySample.CloseDate = System.today();
      opportunitySample.StageName ='Prospecting';
      
      return opportunitySample;
  }
  

/*
* @Method This method  getProduct2 is used to get a  Product2
* @param Method is not having any parameters
* @return Product2 - Method returning instance of  Product2
* @throws exception - Method is not throwing any exception
*/  
 public static Product2 getProduct2() {
      Product2 product2Sample=new Product2();
      product2Sample.Name='Test Product2';

      return product2Sample;
  }


/*
* @Method This method  getQuote is used to get a  Quote
* @param Method is not having any parameters
* @return Quote - Method returning instance of  Quote
* @throws exception - Method is not throwing any exception
*/  
 public static Quote getQuote() {
      Quote quoteSample=new Quote();
      quoteSample.Name='Test Quote';
      insert quoteSample;
      return quoteSample;
  }



}