src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>WOD_Active_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the account is a Web on Demand user</description>
        <label>WEB Active User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WOD_Address__c</fullName>
        <description>URL address</description>
        <label>WEB Address</label>
        <type>Url</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Like_to_Receive_Behr_News_Offers__c</fullName>
        <label>Like to Receive Behr News &amp; Offers</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Occupation__c</fullName>
        <label>Primary Occupation</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architecture, Planner, Designer, Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Materials/Lumber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Products/Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Coverings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &amp; Building Manufacture (Panelized &amp; Log)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance and Title Companies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Exporter - Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing of Modular/Panelized/Log Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masonry/Stone Work/Tile/Plaster Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifamily Development - Affordable Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifamily Development - Condo/Coop Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifamily Development - Market Rate Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifamily General Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Wholesale Dealership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Wall Coverings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planner/Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plumbing/HVAC/Insulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manufacture and/or Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate/Investing/Appraisals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Services_Requested__c</fullName>
        <label>Services Requested</label>
        <picklist>
            <picklistValues>
                <fullName>Color Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery/Factory Tinting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Express Store Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Site Visits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terms/Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Services(s) Not Listed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None Requested</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Behr_Rep_Contact__c</fullName>
        <description>Customer would like for a Behr Rep to contact them</description>
        <inlineHelpText>Indicates if the customer would like  a Behr Rep to contact them</inlineHelpText>
        <label>Behr Rep Contact</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Monthly_Paint_Usage__c</fullName>
        <label>Estimated Monthly Paint Usage</label>
        <picklist>
            <picklistValues>
                <fullName>&lt;50 Gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51-124 Gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;125 Gallons</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Over 45 gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;124 Gallons</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Occupation__c</fullName>
        <label>Primary Occupation</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architecture, Planner, Designer, Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Materials/Lumber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Products/Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Coverings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home &amp; Building Manufacture (Panelized &amp; Log)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance and Title Companies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Exporter - Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing of Modular/Panelized/Log Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masonry/Stone Work/Tile/Plaster Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifamily Development - Affordable Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifamily Development - Condo/Coop Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifamily Development - Market Rate Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifamily General Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Wholesale Dealership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint/Wall Coverings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planner/Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plumbing/HVAC/Insulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manufacture and/or Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate/Investing/Appraisals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Services_Requested__c</fullName>
        <label>Services Requested</label>
        <picklist>
            <picklistValues>
                <fullName>Color Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery/Factory Tinting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Express Store Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Site Visits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terms/Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Services(s) Not Listed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None Requested</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Profession__c</fullName>
        <label>Type of Profession</label>
        <picklist>
            <picklistValues>
                <fullName>MRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remodeler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restoration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WOD_Active_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the LEAD has a Web on Demand active account</description>
        <inlineHelpText>Indicates if the lead has a Web Enabled Business or Web on Demand account</inlineHelpText>
        <label>WEB Active User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WOD_Address__c</fullName>
        <description>Indicates the Web on Demand address for the lead</description>
        <inlineHelpText>Indicates the Web on Demand address for the lead</inlineHelpText>
        <label>WEB Address</label>
        <type>Url</type>
    </fields>
</CustomObject>

src/classes/ProRegistrationSyncTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ProRegistrationSyncTest {

    static testMethod void testSaveProInfo() {
        
        
        /*
        Contact contact = new Contact();
        Account account = new Account();
        contact.AssistantName = 'Assistant';
        contact.AssistantPhone = '714-545-7010';
        contact.FirstName = 'Pro';
        contact.LastName = 'Contractor';
        contact.Email = 'contractor@pchbuilders.com';
        contact.Phone = '714-545-7010';
        lead.Company = 'PCH Builders';
        contact.MailingStreet = '3400 Segerstrom Ave';
        contact.MailingCity = 'Santa Ana';
        contact.MailingState = 'CA';
        contact.MailingPostalCode = '92704';
        contact.Primary_Occupation__c = 'Architect';
        //contact.EstimatedUsage = '40';
        contact.Like_to_Receive_Behr_News_Offers__c = 'Yes';
   */     

        Lead lead = new Lead(
            Company = 'Aron Builders',
            Phone = '814-545-7010',
            FirstName = 'New',
            LastName = 'Pro',            
            Services_Requested__c = 'Job Specification',
            Estimated_Monthly_Paint_Usage__c = '>125 Gallons',
            Behr_Rep_Contact__c = 'Yes',
            Street = '3100 Segerstrom Ave',
            City = 'Newport Beach',
            State = 'CA',
            PostalCode = '92660',
            Type_of_Profession__c = 'Remodeler',
            HasOptedOutOfEmail = true            
            
            
        );

        lead.WOD_Active_User__c = false;
        lead.WOD_Address__c = 'http://www.aronbuilders.com';
        lead.Website = 'http://www.aronbuilders.com';
        
        
        String leadid = ProRegistrationSync.updateProContactInfo(lead);
        System.assert(leadid != null);
        
        String id = ProRegistrationSync.saveProContactInfo(lead);
        
        System.debug('@@@@@@lead:'+lead);
        System.debug('Id of the lead:'+id);
        
        
    }
}