src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Annual_Spend__c</fullName>
        <label>Estimated Annual Spend (All Paint)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <picklist>
            <picklistValues>
                <fullName>Behr In-Store Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behr PPSSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BehrPRO Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Depot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mktg-driven National Event/Trade Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Event/Trade Show</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>Key market segments.</description>
        <inlineHelpText>Segment must be selected. DO NOT select THD Pilot Programs (for internal reporting purposes ONLY).</inlineHelpText>
        <label>Market Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B2B(OEM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exporter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goverment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Painting and Wall Covering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remodeler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THD Pilot Programs</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RPSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RPSM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tier_Level__c</fullName>
        <label>HD Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronze</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Direct_To_Pro_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Direct To Pro Sales</relationshipLabel>
        <relationshipName>Direct_To_Pro_Sales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_HD_Store__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact Phone = HD Store</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current Year</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes_Comments__c</fullName>
        <label>Notes/Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ordered_By__c</fullName>
        <label>Ordered By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Direct To Pro Sales</label>
    <nameField>
        <displayFormat>DTP-{000000000}</displayFormat>
        <label>DTP#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct To Pro Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Behr_Rep_Contact_Number__c</fullName>
        <inlineHelpText>Phone number customer can reach you</inlineHelpText>
        <label>Behr Rep Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Behr_Rep_Email__c</fullName>
        <label>Behr Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Behr_Rep_Name__c</fullName>
        <label>Behr Rep Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitors__c</fullName>
        <label>Competitors</label>
        <picklist>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn-Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden (PRO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden (THD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Lost_Reason__c</fullName>
        <label>Opportunity Lost Reason</label>
        <picklist>
            <picklistValues>
                <fullName>THD Value Prop does not fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THD Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THD does not carry right product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity Sales Process</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Zone1__c</fullName>
        <description>Zone for selection (To be used to populate other zone)</description>
        <label>Selected Zone</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off Zone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>PRODUCT__c</fullName>
        <label>PRODUCT</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone1__c</fullName>
        <label>Zone 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes/Orders</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <formula>Contact.FirstName + &quot; &quot;+  Contact.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Converted_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted to Order</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Quote</fullName>
        <active>true</active>
        <label>Quote</label>
    </recordTypes>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>RPSM__c</fullName>
        <description>Regional Pro Sales Manager</description>
        <label>RPSM Old</label>
        <picklist>
            <picklistValues>
                <fullName>Abe Suleiman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Mahoney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brandon Jones</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brian Emmert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermot McGuire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greg Goodwin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>John Wysor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luke Markes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mike Marienthal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neal Sherman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phillip Hayes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Randy Rivers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spyros Zorbas</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/Test_AccountController.cls
@isTest(SeeAllData=true)
private class Test_AccountController{    

    static testMethod void myUnitTest() {
    
      
    
      RecordType rt = [select id, name 
                     from Recordtype 
                     where sobjectType ='Account' and name = 'Standard Account'];
                     
                     
        Profile p=[SELECT Id FROM profile WHERE name='System Administrator'];
        UserRole ur=new UserRole(Name='CM'); 
        User u=new User(UserRoleid=ur.id,alias = 'proxy456', 
        email='proxy@proxy456.com',emailencodingkey='UTF-8', lastname='proxy456',
        languagelocalekey='en_US',localesidkey='en_US',
        rpsm__c='test',
        profileid = p.Id,timezonesidkey='America/Los_Angeles',username='proxy@proxy456.com',CommunityNickname='proxy456.aaa');
        insert u; 
        Test.starttest();
        Account objparentacc = new Account();
        objparentacc.RecordTypeid = rt.id;
        objparentacc.Name = 'Test Parent Account000';
        objparentacc.Estimated_Annual_Spend__c = 1200;
        objparentacc.Market_Segment__c = 'Exporter';
        objparentacc.Lead_Source__c = 'ARCAT';   
        objparentacc.BillingStreet ='24,marg';
        objparentacc.BillingCity = 'kolkata';
        objparentacc.BillingState = 'Iowa';
        objparentacc.BillingPostalCode = '700061';
        objparentacc.BillingCountry ='United States';
        objparentacc.Tier_Level__c = 'Tier 1';
        insert objparentacc ;
     
        Account a = new Account();
        a.RecordTypeid = rt.id;
        a.ParentId = objparentacc.id;
        a.Name = 'Test Account9';
        a.Estimated_Annual_Spend__c = 1200;
        a.Market_Segment__c = 'Exporter';
        a.Lead_Source__c = 'ARCAT';   
        a.BillingStreet ='24,marg';
        a.BillingCity = 'kolkata';
        a.BillingState = 'Iowa';
        a.BillingPostalCode = '700061';
        a.BillingCountry ='United States';
        a.Tier_Level__c = 'Tier 1';
        a.ownerid=u.id;
        insert a;
        
     System.currentPageReference().getParameters().put('id', a.id);
     ApexPages.currentPage().getParameters().put('retURL',a.id);
     ApexPages.StandardController controller=new ApexPages.StandardController(a);  
    // Behr_AccountController_US acc = new Behr_AccountController_US(controller);
   //  acc.getAccount();
   //  acc.getContact();
   //  acc.getOpportunity();
  //   acc.getActivity();
   //  acc.getAccountteam();
   //  acc.getCustomerPayoyts();
    // acc.getReasonforLostOpp();
   //  acc.getDashboard();
   //  acc.getOrder();

       
 
        Contact c = new Contact();
        c.AccountId = a.id;
        c.LastName = 'contact';
        c.FirstName = 'test';
        c.phone = '9876543210';
        c.Email = 'test@gmail.com';
        c.LeadSource = 'ARCAT'; 
        insert c;
        
       
      
      List<Account> objactivityHistory = [Select (Select WhoID, Subject, IsTask, 
                                                      ActivityDate, Owner.name, Status                                    
                                                      From ActivityHistories
                                                      Where AccountId =:a.id)
                                           From Account
                                           WHERE id =:a.id];
  
      AccountTeamMember objmember = new AccountTeamMember ();
      objmember.UserId = u.id;
      objmember.AccountId = a.id;
      insert objmember;
       Test.StopTest();
      
     
   
                           
      

    }
     static testMethod void QuoteTestMethod() {
         test.startTest();
          RecordType rt = [select id, name 
         from Recordtype 
         where sobjectType ='Account' and name = 'Standard Account'];
          Account a = new Account();
        a.RecordTypeid = rt.id;        
        a.Name = 'Test Account9';
        a.Estimated_Annual_Spend__c = 1200;
        a.Market_Segment__c = 'Exporter';
        a.Lead_Source__c = 'ARCAT';   
        a.BillingStreet ='24,marg';
        a.BillingCity = 'kolkata';
        a.BillingState = 'Iowa';
        a.BillingPostalCode = '700061';
        a.BillingCountry ='United States';
        a.Tier_Level__c = 'Tier 1';        
        insert a;
        
        Contact c = new Contact();
        c.AccountId = a.id;
        c.LastName = 'contact';
        c.FirstName = 'test';
        c.phone = '9876543';
        c.Email = 'test@gmail.com';
        c.LeadSource = 'ARCAT'; 
        insert c;
        
        Opportunity o =new Opportunity();
        o.AccountId =a.id;
        o.StageName = 'Position/Prepare';
        o.Primary_Contact__c = c.id;
        o.CloseDate = system.today() + 10;
        o.Amount = 765;
        o.Behr_Rep_Contact_Number__c = '9876543210';
        o.Behr_Rep_Email__c = 'testopp@gmail.com';
        o.Behr_Rep_Name__c = 'test rep';
        o.Name = 'test Opp';
        o.Opportunity_Type__c = 'Bid';
        o.Type = 'THD';
        insert o;
        
        Product2 objproduct = new Product2 (Name='Test Product', IsActive=true);
       
        insert objproduct;
        
         /*Pricebook2 objPriceBook= new Pricebook2(Name = 'Behr/Kilz Pro Pricing',
                                                  IsActive = true);
           insert objPriceBook;                                     */
           
        Pricebook2 objPriceBook = [select id from Pricebook2 where isStandard=true limit 1];  
       
        
        system.debug('@@@@@@@@@@@@@@@@@@@@@@@@@'+objPriceBook);
        
        PricebookEntry objPriceBookEntry = new PricebookEntry(Pricebook2Id =objPriceBook.Id,
                                           Product2Id = objproduct.Id,UnitPrice = 100,IsActive = true,
                                           UseStandardPrice=false);
        insert objPriceBookEntry;
        
         OpportunityLineItem oplineitem=new OpportunityLineItem();
        
        oplineitem.OpportunityId=o.id ;
        oplineitem.PricebookEntryId=objPriceBookEntry .id;
        oplineitem.Quantity=2;
        oplineitem.TotalPrice=10.00;
        oplineitem.Zone1__c ='1';
        //oplineitem.UnitPrice=12.00;
        insert oplineitem;
        delete oplineitem;
        
        Quote q = new Quote();
        q.name = 'Q-001';
        q.OpportunityId = o.id;
        q.Tax = 10;
        q.ShippingHandling = 20000;  
        //q.phone = c.phone;
        q.Email =  c.Email;  
        q.Pricebook2Id = objPriceBook.id;
        q.ShippingState='Oregon';
        insert q;
        
        QuoteLineItem ql = new QuoteLineItem ();       
        ql.QuoteId = q.id;
        ql.UnitPrice = 10;
        ql.Quantity = 2;
        ql.PricebookEntryId = objPriceBookEntry.id;
        insert ql;
        
        //For Behr_QuoteAll trigger
        
        q.Converted_to_Order__c=true;
        update q;
         Test.StopTEst();
         
     }
 /*   static testMethod void createdummyoptyTest() {
        test.startTest();
         RecordType rt = [select id, name 
         from Recordtype 
         where sobjectType ='Account' and name = 'Standard Account'];
        Account objparentacc = new Account();
        objparentacc.RecordTypeid = rt.id;
        objparentacc.Name = 'Test Parent Account000';
        objparentacc.Estimated_Annual_Spend__c = 1200;
        objparentacc.Market_Segment__c = 'Exporter';
        objparentacc.Lead_Source__c = 'ARCAT';   
        objparentacc.BillingStreet ='24,marg';
        objparentacc.BillingCity = 'kolkata';
        objparentacc.BillingState = 'Iowa';
        objparentacc.BillingPostalCode = '700061';
        objparentacc.BillingCountry ='United States';
        objparentacc.Tier_Level__c = 'Tier 1';
        insert objparentacc ;     
         //for  Behr_createdummyopty_us class
      Behr_createdummyopty_us.createopty(objparentacc.Id);            
        test.STopTest();
    }*/
     static testMethod void AccountControllerTest() {
         Test.StartTest();
         UserRole ur=new UserRole(Name='CM'); 
         Profile p=[SELECT Id FROM profile WHERE name='System Administrator'];
        User u=new User(UserRoleid=ur.id,alias = 'proxy456', 
        email='proxy@proxy456.com',emailencodingkey='UTF-8', lastname='proxy456',
        languagelocalekey='en_US',localesidkey='en_US',
        rpsm__c='test',
        profileid = p.Id,timezonesidkey='America/Los_Angeles',username='proxy@proxy456.com',CommunityNickname='proxy456.aaa');
        insert u; 
        RecordType rt = [select id, name 
         from Recordtype 
         where sobjectType ='Account' and name = 'Standard Account'];
        Account objparentacc = new Account();
        objparentacc.RecordTypeid = rt.id;
        objparentacc.Name = 'Test Parent Account000';
        objparentacc.Estimated_Annual_Spend__c = 1200;
        objparentacc.Market_Segment__c = 'Exporter';
        objparentacc.Lead_Source__c = 'ARCAT';   
        objparentacc.BillingStreet ='24,marg';
        objparentacc.BillingCity = 'kolkata';
        objparentacc.BillingState = 'Iowa';
        objparentacc.BillingPostalCode = '700061';
        objparentacc.BillingCountry ='United States';
        objparentacc.Tier_Level__c = 'Tier 1';
        insert objparentacc ;           
        Account a = new Account();
        a.RecordTypeid = rt.id;
        a.ParentId = objparentacc.id;
        a.Name = 'Test Account9';
        a.Estimated_Annual_Spend__c = 1200;
        a.Market_Segment__c = 'Exporter';
        a.Lead_Source__c = 'ARCAT';   
        a.BillingStreet ='24,marg';
        a.BillingCity = 'kolkata';
        a.BillingState = 'Iowa';
        a.BillingPostalCode = '700061';
        a.BillingCountry ='United States';
        a.Tier_Level__c = 'Tier 1';
        a.ownerid=u.id;
        insert a;
        
        Opportunity o =new Opportunity();
        o.AccountId =a.id;
        o.StageName = 'Position/Prepare';
        o.CloseDate = system.today() + 10;
        o.Amount = 765;
        o.Behr_Rep_Contact_Number__c = '9876543210';
        o.Behr_Rep_Email__c = 'testopp@gmail.com';
        o.Behr_Rep_Name__c = 'test rep';
        o.Name = 'test Opp';
        o.Opportunity_Type__c = 'Bid';
        insert o;
        System.currentPageReference().getParameters().put('id', a.id);
         ApexPages.currentPage().getParameters().put('retURL',a.id);
        ApexPages.StandardController controller1=new ApexPages.StandardController(a);  
       // Behr_AccountController_US acc1 = new Behr_AccountController_US(controller1);  
      //  acc1.getAccount();
      //  acc1.getContact();
     //   acc1.getOpportunity();
        o.Opportunity_Type__c = 'Potential';
        update o;
       // acc1.getOpportunity(); 
        o.StageName = 'Lost';
        o.Opportunity_Lost_Reason__c = 'Price';
        o.Competitors__c = 'ICI';
        update o;
        
      //  acc1.getOpportunity(); 
   //     acc1.getActivity();
    //    acc1.getAccountteam();
    //    acc1.getCustomerPayoyts();
   //     acc1.getReasonforLostOpp();
    //    acc1.getDashboard();
    //    acc1.getOrder();       
       // acc1.getoppdashboard();
         Test.StopTest();
     }
     static testMethod void myUnitTest1() {
         Test.StartTest();
         UserRole ur=new UserRole(Name='CM'); 
         Profile p=[SELECT Id FROM profile WHERE name='System Administrator'];
        User u=new User(UserRoleid=ur.id,alias = 'proxy456', 
        email='proxy@proxy456.com',emailencodingkey='UTF-8', lastname='proxy456',
        languagelocalekey='en_US',localesidkey='en_US',
        rpsm__c='test',
        profileid = p.Id,timezonesidkey='America/Los_Angeles',username='proxy@proxy456.com',CommunityNickname='proxy456.aaa');
        insert u; 
         RecordType rt = [select id, name 
         from Recordtype 
         where sobjectType ='Account' and name = 'Standard Account'];
         Account objparentacc = new Account();
        objparentacc.RecordTypeid = rt.id;
        objparentacc.Name = 'Test Parent Account000';
        objparentacc.Estimated_Annual_Spend__c = 1200;
        objparentacc.Market_Segment__c = 'Exporter';
        objparentacc.Lead_Source__c = 'ARCAT';   
        objparentacc.BillingStreet ='24,marg';
        objparentacc.BillingCity = 'kolkata';
        objparentacc.BillingState = 'Iowa';
        objparentacc.BillingPostalCode = '700061';
        objparentacc.BillingCountry ='United States';
        objparentacc.Tier_Level__c = 'Tier 1';
        insert objparentacc ;         
        Account a = new Account();
        a.RecordTypeid = rt.id;
        a.ParentId = objparentacc.id;
        a.Name = 'Test Account9';
        a.Estimated_Annual_Spend__c = 1200;
        a.Market_Segment__c = 'Exporter';
        a.Lead_Source__c = 'ARCAT';   
        a.BillingStreet ='24,marg';
        a.BillingCity = 'kolkata';
        a.BillingState = 'Iowa';
        a.BillingPostalCode = '700061';
        a.BillingCountry ='United States';
        a.Tier_Level__c = 'Tier 1';
        a.ownerid=u.id;
        insert a;
        Product2 objproduct = new Product2 (Name='Test Product', IsActive=true);
       
       // insert objproduct;
          //For AddPriceforProduct trigger (**REMOVED 12/3/14 to allow for removal of trial object)
       //   Trial_Paint__c objtrial =  new Trial_Paint__c();
     //     objtrial.Account__c = objparentacc.id;
      //    objtrial.Product__c =objproduct.id;
 
      //    insert objtrial;  
          
    //      objtrial.Price__c =0;
     //     objtrial.Product__c = null;
    //      update objtrial;
          
           //Direct To Pro sales 
           Direct_To_Pro_Sales__c dtp=new Direct_To_Pro_Sales__c();
           dtp.Account_Name__c=a.id;
           dtp.Account_Updated__c=true;
           dtp.Contact_Name__c='fhfbgjhgj';
           dtp.Contact_Phone__c='4689';
           dtp.Contact_Phone_HD_Store__c=true;
           dtp.Current_Year__c=true;
           dtp.Notes_Comments__c='skjhiuyfd';
           dtp.Ordered_By__c='aaaaaaa';
           insert dtp;
         Test.StopTest();
         
     }
}