src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Estimated_Annual_Spend__c</fullName>
        <label>Estimated Annual Spend (All Paint)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <picklist>
            <picklistValues>
                <fullName>Behr In-Store Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behr PPSSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BehrPRO Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Depot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mktg-driven National Event/Trade Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Event/Trade Show</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>Key market segments.</description>
        <inlineHelpText>Segment must be selected. DO NOT select THD Pilot Programs (for internal reporting purposes ONLY).</inlineHelpText>
        <label>Market Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B2B(OEM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exporter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goverment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Painting and Wall Covering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remodeler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THD Pilot Programs</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RPSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RPSM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tier_Level__c</fullName>
        <label>HD Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronze</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Behr_Rep_Contact_Number__c</fullName>
        <inlineHelpText>Phone number customer can reach you</inlineHelpText>
        <label>Behr Rep Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Behr_Rep_Email__c</fullName>
        <label>Behr Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Behr_Rep_Name__c</fullName>
        <label>Behr Rep Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity Sales Process</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <description>Behr Rep Mobile number</description>
        <label>Mobile Number</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <description>Provide users with the ability to place orders in Salesforce.These orders will then be distributed to other systems to allow easier order entry.</description>
        <label>Order</label>
    </recordTypes>
    <recordTypes>
        <fullName>Quote</fullName>
        <active>true</active>
        <label>Quote</label>
    </recordTypes>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Color_Vendor__c</fullName>
        <label>Color Vendor</label>
        <picklist>
            <picklistValues>
                <fullName>Behr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn-Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Tint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant1__c</fullName>
        <label>Colorant 2</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant2__c</fullName>
        <label>Colorant 3</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant3__c</fullName>
        <label>Colorant 4</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant__c</fullName>
        <label>Colorant 1</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X384ths_1__c</fullName>
        <label>384ths 1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_2__c</fullName>
        <label>384ths 2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_3__c</fullName>
        <label>384ths 3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_4__c</fullName>
        <label>384ths 4</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_5__c</fullName>
        <label>384ths 5</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>RPSM__c</fullName>
        <description>Regional Pro Sales Manager</description>
        <label>RPSM Old</label>
        <picklist>
            <picklistValues>
                <fullName>Abe Suleiman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Mahoney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brandon Jones</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brian Emmert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermot McGuire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greg Goodwin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>John Wysor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luke Markes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mike Marienthal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neal Sherman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phillip Hayes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Randy Rivers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spyros Zorbas</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/Test_Behr_orderlineitemedit.cls
@isTest(SeeAllData=true)
private class Test_Behr_orderlineitemedit{    

    static testMethod void orderlineitemedit() {
    
     RecordType rt = [select id, name 
                     from Recordtype 
                     where sobjectType ='Account' and name = 'Standard Account'];
                     
                     
                      Profile p=[SELECT Id FROM profile WHERE name='System Administrator'];
        UserRole ur=new UserRole(Name='CM'); 
        User u=new User(UserRoleid=ur.id,alias = 'proxy456', 
        email='proxy@proxy456.com',emailencodingkey='UTF-8', lastname='proxy456',
        languagelocalekey='en_US',localesidkey='en_US',
        rpsm__c='test',
        profileid = p.Id,timezonesidkey='America/Los_Angeles',username='proxy@proxy456.com',CommunityNickname='proxy456.aaa');
        insert u; 
        Test.starttest();
        Account objparentacc = new Account();
            objparentacc.RecordTypeid = rt.id;
            objparentacc.Name = 'Test Parent Account123456776543';
            objparentacc.Estimated_Annual_Spend__c = 1200;
            objparentacc.Market_Segment__c = 'Exporter';
            objparentacc.Lead_Source__c = 'ARCAT';   
            objparentacc.BillingStreet ='24,marg';
            objparentacc.BillingCity = 'kolkata';
            objparentacc.BillingState = 'Iowa';
            objparentacc.BillingPostalCode = '700061';
            objparentacc.BillingCountry ='United States';
            objparentacc.Tier_Level__c = 'Tier 1';
        insert objparentacc ;
        
        Opportunity o =new Opportunity();
            o.AccountId =objparentacc.id;
            o.StageName = 'Position/Prepare';
            o.CloseDate = system.today() + 10;
            o.Amount = 765;
            o.Behr_Rep_Contact_Number__c = '9876543210';
            o.Behr_Rep_Email__c = 'testopp@gmail.com';
            o.Behr_Rep_Name__c = 'test rep';
            o.Name = 'test Opp';
            o.Opportunity_Type__c = 'Bid';
        insert o;
        
          RecordType rt1 = [select id, name 
                     from Recordtype 
                     where sobjectType ='Quote' and name = 'Order'];
        
        Product2 objproduct = new Product2 (Name='Test Product', IsActive=true);
         insert objproduct;
        
         Pricebook2 objPriceBook = [select id from Pricebook2 where isStandard=true limit 1];  
        
          PricebookEntry objPriceBookEntry = new PricebookEntry(Pricebook2Id =objPriceBook.Id,
                                           Product2Id = objproduct.Id,UnitPrice = 100,IsActive = true,
                                           UseStandardPrice=false);
         Quote q = new Quote();
            q.name = 'Q-001';
            q.OpportunityId = o.id;
            q.Tax = 10;
            q.ShippingHandling = 20000;  
            q.Mobile_Number__c = '9876543210';
            q.Email=  'testopp@gmail.com';
            q.recordtypeid=rt1.id;  
            q.Pricebook2Id = objPriceBook.id;
            q.ShippingState='Oregon';
         insert q;
    
       
         insert objPriceBookEntry;
         
         QuoteLineItem ql = new QuoteLineItem ();       
            ql.QuoteId = q.id;
            ql.UnitPrice = 10;
            ql.Quantity = 2;
            ql.Color_Vendor__c='Color Formula';
            ql.X384ths_1__c=1;
            ql.X384ths_2__c=1;
            ql.X384ths_3__c=1;
            ql.X384ths_4__c=1;
            ql.X384ths_5__c=1;
            ql.Colorant__c='AXL';
            ql.Colorant1__c='RUL';
            ql.Colorant2__c='VUL';
            ql.Colorant3__c='DL';
            ql.Colorant4__c='EL';
            ql.OZ_1__c=1;
            ql.OZ_2__c=1;
            ql.OZ_3__c=1;
            ql.OZ_4__c=1;
            ql.OZ_5__c=11;
                
            ql.PricebookEntryId =objPriceBookEntry.id;
         insert ql;
         Test.StopTest();
         
         System.currentPageReference().getParameters().put('id', ql.id);
         System.currentPageReference().getParameters().put('retURL', q.id);
         ApexPages.StandardController controller1=new ApexPages.StandardController(ql); 
         Behr_orderLineItemEdit orderLineItemEdit =new Behr_orderLineItemEdit(controller1);
         orderLineItemEdit .onchange1();
         orderLineItemEdit .redirect();
         orderLineItemEdit .save1();
         
    
    
    }
    }