src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_Supplier__c</fullName>
        <label>Primary Supplier (Non Behr)</label>
        <picklist>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex (Frazee/Kwal/Color Wheel/Parker)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG (Olympic/Pittsburgh/Porter)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin-Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valspar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Annual_Spend__c</fullName>
        <label>Estimated Annual Spend (All Paint)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>Key market segments.</description>
        <inlineHelpText>Segment must be selected. DO NOT select THD Pilot Programs (for internal reporting purposes ONLY).</inlineHelpText>
        <label>Market Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B2B(OEM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exporter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goverment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Painting and Wall Covering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remodeler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THD Pilot Programs</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>THD_Home_Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>THD store account originally signed up in.</description>
        <inlineHelpText>THD location account initially signed up.</inlineHelpText>
        <label>THD Home Store</label>
        <referenceTo>Home_Depot_Store__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tier_Level__c</fullName>
        <label>HD Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronze</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Actual_Sales__c.object
<CustomObject>
    <description>New object that will contain header and line items against opportunity and account</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Actual Sales</relationshipLabel>
        <relationshipName>Actual_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Actual Sales</relationshipLabel>
        <relationshipName>Actual_Sales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Order__c</fullName>
        <description>used for external upsert only.</description>
        <externalId>true</externalId>
        <label>SAP Order</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Order</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Actual Sales</label>
    <nameField>
        <label>Record ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actual Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Name__c</fullName>
        <label>Store Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Direct_Onboarding__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Onboardings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Supplier__c</fullName>
        <label>Current Supplier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <formula>TEXT(Account_Name__r.Market_Segment__c)</formula>
        <label>Market Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending RPSM Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending RVP Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending SVP Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Account Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Setup Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by RPSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by RVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Direct Onboarding</label>
    <nameField>
        <displayFormat>AO-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Home_Depot_Store__c.object
<CustomObject>
    <description>Details of the Home Depot Store selling BEHR products</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Name__c</fullName>
        <label>Market Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Number__c</fullName>
        <label>Market Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Store_Label__c</fullName>
        <label>SAP Store Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Name__c</fullName>
        <label>Store Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store_Phone__c</fullName>
        <label>Store Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>THD_DM__c</fullName>
        <description>Home Depot District Manager</description>
        <label>THD DM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>THD_RMM__c</fullName>
        <label>THD RMM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>THD_Region__c</fullName>
        <label>THD Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>THD_Territory__c</fullName>
        <label>THD Territory</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>THD Stores</label>
    <nameField>
        <label>THD Store Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>THD Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Behr_Rep_Contact_Number__c</fullName>
        <inlineHelpText>Phone number customer can reach you</inlineHelpText>
        <label>Behr Rep Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Ship To City details.</description>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Ship To State details</description>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity Sales Process</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
</CustomObject>

src/objects/Ownership_Approval__c.object
<CustomObject>
    <description>This object will provide the ability for a PSR to request ownership changes at the account level.  A PSR will also be able to request approval for Actual Sales that are currently associated to the wrong opportunity to be moved to the correct opportunity</description>
    <fields>
        <fullName>ActualSales__c</fullName>
        <label>Actual Sales</label>
        <referenceTo>Actual_Sales__c</referenceTo>
        <relationshipName>Ownership_Approvals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>New_Opportunity_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Actual Sales Updates</relationshipLabel>
        <relationshipName>Ownership_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Actual Sales Update</label>
    <nameField>
        <displayFormat>OA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Sales Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order#</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <description>Provide users with the ability to place orders in Salesforce.These orders will then be distributed to other systems to allow easier order entry.</description>
        <label>Order</label>
    </recordTypes>
    <recordTypes>
        <fullName>Quote</fullName>
        <active>true</active>
        <label>Quote</label>
    </recordTypes>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>RVP__c</fullName>
        <label>RVP</label>
        <relationshipName>RVP_User</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>SVP__c</fullName>
        <label>SVP</label>
        <relationshipName>SVP_User</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
</CustomObject>

src/classes/Test_Utility_BehrClass.cls
@isTest(SeeAllData=true)
public class Test_Utility_BehrClass {
     
   public User insertUser(){ 
     Profile p = [select id from profile where name='System Administrator'];
     //       Test.startTest();     
       User RVP = new User(alias = 'standt', email='standarduser@testorg.com', 
            emailencodingkey='UTF-8', lastname='RVP', languagelocalekey='en_US', 
            localesidkey='en_US', profileid = p.Id, 
            timezonesidkey='America/Los_Angeles', username='standarduserRVP@testorg.com');
            insert RVP;
            
       User SVP = new User(alias = 'standt', email='standarduser@testorg.com', 
            emailencodingkey='UTF-8', lastname='SVP', languagelocalekey='en_US', 
            localesidkey='en_US', profileid = p.Id, 
            timezonesidkey='America/Los_Angeles', username='standarduserSVP@testorg.com');
            insert SVP;
            
       User u = new User(alias = 'standt',Country =' United States',PostalCode ='987654',State = 'Texas',City = 'Austin',Street ='Test Street', email='standarduser@testorg.com', 
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
            localesidkey='en_US', profileid = p.Id, RVP__c = RVP.Id, SVP__c = SVP.Id, 
            timezonesidkey='America/Los_Angeles', username='standarduserTEST@testorg.com');
            
            insert u;
    //       Test.stopTest();
            return u;
            
            }
            
       public Home_Depot_Store__c insertTHD(){
            Home_Depot_Store__c THDSt = new Home_Depot_Store__c();
            THDSt.Name ='THDStore-Test';
            THDSt.Store_Name__c = 'Store-Test';
            THDSt.SAP_Store_Label__c ='SAP-Store';
            THDSt.Street_Address__c = '8th-Street';
            THDSt.City__c = 'Chennai';
            THDSt.State__c = 'Tamilnadu';
            THDSt.Zip_Code__c = '600050';
            THDSt.Store_Phone__c = '98765436';
            THDSt.Market_Number__c = '123';
            THDSt.Market_Name__c = 'Market';
            THDSt.THD_Territory__c = 'Territory';
            THDSt.THD_Region__c = 'region';
            THDSt.THD_DM__c = 'DM';
            THDSt.THD_RMM__c = 'RMM';
            insert THDSt;
            return THDSt;
            
            } 
       
       public Account insertAccount(){
     //      Test.startTest();
           RecordType rt = [select id, name 
                         from Recordtype 
                         where sobjectType ='Account' and name = 'Standard Account'];                     
            Home_Depot_Store__c THDSt = new Home_Depot_Store__c();
            THDSt = insertTHD();
            Account acc = new Account();            
            acc.RecordTypeid = rt.id;
            acc.Name = 'Test Parent Accountnvbhdbffn';
            acc.Estimated_Annual_Spend__c = 1200;
            acc.Market_Segment__c = 'Exporter';           
            acc.BillingStreet ='24,marg';
            acc.Type = 'Direct Only';
            acc.BillingPostalCode = '700061';
            acc.BillingCountry ='Mexico';
            acc.Tier_Level__c = 'Tier 1';
            acc.THD_Home_Store__c = THDSt.id;
            acc.Current_Supplier__c = 'Glidden';
            insert acc;
      //      Test.stopTest();
            return acc;
            
            
            }     
      
       public Contact insertContact(){     
      //      Test.startTest();
            Id Accid = insertAccount().id ;
            RecordType contactRT = [select id, name from Recordtype where sobjectType ='Contact' and name = 'US Contact'];
            Contact c = new contact();
            c.AccountId = Accid;
            c.LastName = 'Tester';
            c.RecordTypeId = ContactRT.Id ;
            c.FirstName = 'TestUser' ;
            c.Salutation = 'Mr.';
            c.Phone = '1234567';
            insert c;
      //      Test.stopTest();            
            return c;
            
            
            }
            
       Public Actual_Sales__c insertActualSales(String DummyPurchase){
            
            Opportunity opp= new Opportunity();
            opp = insertOpportunity();
            
            Actual_Sales__c newActS = new Actual_Sales__c();
            newActS.Account_Name__c = opp.AccountId ;
            newActS.Opportunity__c = opp.Id ;
            newActS.Name = 'test Actual Sales' ;
            newActS.Purchase_Order__c = DummyPurchase;
            newActS.SAP_Order__c = 'Test SAP Order';
            insert newActS;
            return newActS;
            
            }
            
       public Ownership_Approval__c insertOwnershipApp(){
            Opportunity opp = new Opportunity();
            opp = insertOpportunity();
            Actual_Sales__c aSale = new Actual_Sales__c();
            String s= 'FirstTime';
            aSale = insertActualSales(s);
            Ownership_Approval__c oA = new Ownership_Approval__c();            
            oA.New_Opportunity_Entry__c = opp.Id;
            oA.ActualSales__c = aSale.id;
            oA.Status__c = 'Approved';
            insert oA;
            return oA;
            
            }
            
       public Opportunity insertOpportunity (){
            
   //        Test.startTest();            
            Contact newContact = new Contact();
            newContact = insertContact();                        
            RecordType opportunityRT = [select id, name from Recordtype where sobjectType ='Opportunity' and name = 'Opportunity'];
            Opportunity o =new Opportunity();
            o.AccountId = newContact.AccountId ;
            o.StageName = 'Position/Prepare';
            o.CloseDate = system.today() + 10;
            o.Amount = 765;
            o.Behr_Rep_Contact_Number__c = '9876543210';
            o.Behr_Rep_Email__c = 'testopp@gmail.com';
            o.Behr_Rep_Name__c = 'test rep';
            o.Name = 'test Opp';
            o.Opportunity_Type__c = 'Bid';
            o.Primary_Contact__c = newContact.Id  ;
            o.Street__c = 'Oppty Street';
            o.City__c = 'Oppty City';
            o.State__c = 'Alabama';
            o.Zipcode__c = '123456';
            o.Country__c = 'United States';
            insert o;
     //       Test.stopTest();
            return o;
            
            
            }
            
         public Account insertParentAccount(){
             
            Account acc = new Account();
            acc = insertAccount();
            Account acc1 = new Account();
             RecordType rt = [select id, name 
                         from Recordtype 
                         where sobjectType ='Account' and name = 'Standard Account'];                                                 
             acc1.RecordTypeid = rt.id;
             acc1.Name = 'Test Parent Accountnvbhdbffn';
             acc1.Estimated_Annual_Spend__c = 1200;
             acc1.Market_Segment__c = 'Exporter';           
             acc1.BillingStreet ='24,marg';
             acc1.Type = 'Direct Only';
             acc1.BillingPostalCode = '700061';
             acc1.BillingCountry ='Mexico';
             acc1.Tier_Level__c = 'Tier 1';
             acc1.Current_Supplier__c = 'Glidden';
             acc1.ParentId = acc.Id; 
             insert acc1;
             return acc1;
             
             }   
            
         public Product2 insertProduct2(){   
     //       Test.startTest();
            Product2 pr = new Product2();
            pr.Name = 'TestProduct';
            pr.IsActive = true;
            insert pr;
     //       Test.stopTest();
            return pr;
            
            }
            
         public Pricebook2 insertPricebook2 (){   
    //        Test.startTest();
            Pricebook2 PrBk = new Pricebook2();
            PrBk.IsActive = true;
            PrBk.Name = 'Test PriceBook';
            insert PrBk;
     //       Test.stopTest();
            return PrBk;
            
            
            }
         
         public PricebookEntry insertPricebookEntry (){
            
      //      Test.startTest();
            Id prId = insertProduct2().Id; 
            Pricebook2 standard = [Select Id, Name, IsActive From Pricebook2 where IsStandard = true LIMIT 1];
            if (!standard.isActive) {
            standard.isActive = true;
            update standard;
            }    
         // pricebook2 standardpb = [select id from pricebook2 where isstandard = true];           
         // List<Pricebook2> PriceList = [SELECT id, Name from Pricebook2 WHERE isStandard = true LIMIT 1];
         // List<PriceBookEntry> priceBookList = [SELECT Id, Product2Id, Product2.Id, Product2.Name FROM PriceBookEntry WHERE /* Product2Id='certain_id' AND */ PriceBook2.isStandard=true LIMIT 1];
         // pricebook2 custompb = new pricebook2(name='test',isactive=true);
         // insert custompb;
       //   pricebookentry standardprice = new pricebookentry( product2id = prod.id, pricebook2id = standardpb.id, unitprice = 4.99), customprice = new pricebookentry( product2id = prod.id, pricebook2id = custompb.id, usestandardprice = true );
            
     //      PricebookEntry PBentry = new PricebookEntry();             
     //       PBentry.Pricebook2Id = standardpb.Id;
      //      PBentry.Product2Id = prId;
      //      PBentry.UnitPrice= 500;
      //      insert PBentry;
            
        
            
            PricebookEntry PBentrynew = new PricebookEntry();
            PBentrynew.IsActive = true; 
            PBentrynew.Pricebook2Id = standard.Id;
            PBentrynew.Product2Id = prId;            
       //   PBentrynew.usestandardprice = true;
            PBentrynew.UnitPrice= 500;
            insert PBentrynew;
            
            
      //      Test.stopTest();
            return PBentrynew;
            
            
            }          
            
          public Quote insertQuote(){
            
      //      Test.startTest();
            Pricebook2 standard = [Select Id, Name, IsActive From Pricebook2 where IsStandard = true AND IsActive = true LIMIT 1];
            Id oId = insertOpportunity().Id;
            RecordType rt1 = [select id, name from Recordtype where sobjectType ='Quote' and name = 'Quote'];
            Quote q = new Quote();
            q.name = 'Q-001';
            q.recordtypeId=rt1.id;
            q.OpportunityId = oid;
            q.Tax = 10;
            q.ShippingHandling = 20000;  
            q.Phone = '4443333' ;
            q.ShippingState = 'Arizona';
            q.Email_Address__c =  'testopp@gmail.com';
            q.Pricebook2Id = standard.Id;  
            insert q;
     //       Test.stopTest();
            return q;
            
            
            }
       
        public Direct_Onboarding__c insertDirectOnboarding(){
        
        //    Test.startTest();
            Id accId = insertAccount().id;         
            Direct_Onboarding__c DirOnb = new Direct_Onboarding__c();     
            DirOnb.Account_Name__c = accId;
            DirOnb.Masco_Subsidiary__c = 'true';
            DirOnb.Status__c = 'Pending Credit Review';
            insert DirOnb;
       //     Test.stopTest();
            return DirOnb;
            
            
            }
            
        public Case insertCase(){    
            
         //   Test.startTest();
            Opportunity opp= new Opportunity();
            opp = insertOpportunity();
            RecordType caseRT = [select id, name from Recordtype where sobjectType ='Case' and name = 'Color Book/Board'];
            date myDate = date.today();
            date newDate = myDate.addDays(25);            
            Case nCase = new Case();
            nCase.AccountId = opp.AccountId ;                   
            nCase.Date_Needed_By__c = newDate ;
            nCase.RecordTypeId = caseRT.Id;
            nCase.Color_BookBoard_Type__c = 'Color Book';
            nCase.Opportunity__c = opp.id;
            insert nCase;
        //    Test.stopTest();
            return ncase;
            
            
            }
            
        
       
       }