src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_Supplier__c</fullName>
        <label>Primary Supplier (Non Behr)</label>
        <picklist>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex (Frazee/Kwal/Color Wheel/Parker)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG (Olympic/Pittsburgh/Porter)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin-Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valspar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Color_BookBoard_Type__c</fullName>
        <label>Color Book/Board Type</label>
        <picklist>
            <picklistValues>
                <fullName>Color Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Board</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Submittal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close Out Book</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Needed_By__c</fullName>
        <inlineHelpText>Does Not Include Ship Time</inlineHelpText>
        <label>Date Needed By</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Job</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shop Ship to</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Color_for_orders__c.object
<CustomObject>
    <description>join for line items to color</description>
    <fields>
        <fullName>Competitor_Color__c</fullName>
        <label>Competitor Color</label>
        <referenceTo>Competitor_Color__c</referenceTo>
        <relationshipName>Color_for_orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Color For Orders</label>
    <nameField>
        <label>Color for orders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color For Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Competitor_Color__c.object
<CustomObject>
    <description>All colors with competitor, code and description.</description>
    <fields>
        <fullName>Color_Brand__c</fullName>
        <description>Brand name of competitor color</description>
        <label>Color Brand</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Name__c</fullName>
        <label>Color Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_code__c</fullName>
        <label>Color Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Competitor Color</label>
    <nameField>
        <label>Color Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Color</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/competitor_colors__c.object
<CustomObject>
    <description>join between scheme and competitor color</description>
    <fields>
        <fullName>Competitor_Color__c</fullName>
        <label>Color</label>
        <referenceTo>Competitor_Color__c</referenceTo>
        <relationshipLabel>Color Selection</relationshipLabel>
        <relationshipName>competitor_colors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scheme__c</fullName>
        <label>Scheme</label>
        <referenceTo>Scheme__c</referenceTo>
        <relationshipName>competitor_colors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>of_draw_downs__c</fullName>
        <defaultValue>1</defaultValue>
        <label># of draw downs</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Color Selection</label>
    <nameField>
        <label>competitor colors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Selection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Direct_Onboarding__c.object
<CustomObject>
    <fields>
        <fullName>Current_Supplier__c</fullName>
        <label>Current Supplier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Direct Onboarding</label>
    <nameField>
        <displayFormat>AO-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Behr_Rep_Contact_Number__c</fullName>
        <inlineHelpText>Phone number customer can reach you</inlineHelpText>
        <label>Behr Rep Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Behr_Rep_Email__c</fullName>
        <label>Behr Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Behr_Rep_Name__c</fullName>
        <label>Behr Rep Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Ship To City details.</description>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitors__c</fullName>
        <label>Competitors</label>
        <picklist>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn-Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden (PRO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden (THD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Ship To Country details.</description>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Ship To State details</description>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Ship To State details</description>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <description>Ship To Zipcode details</description>
        <label>Zipcode</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity Sales Process</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Zone1__c</fullName>
        <description>Zone for selection (To be used to populate other zone)</description>
        <label>Selected Zone</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off Zone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Converted_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted to Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <description>Provide users with the ability to place orders in Salesforce.These orders will then be distributed to other systems to allow easier order entry.</description>
        <label>Order</label>
    </recordTypes>
    <recordTypes>
        <fullName>Quote</fullName>
        <active>true</active>
        <label>Quote</label>
    </recordTypes>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Color_Name_Code1__c</fullName>
        <label>Color Name/Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Vendor__c</fullName>
        <label>Color Vendor</label>
        <picklist>
            <picklistValues>
                <fullName>Behr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn-Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Tint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Scheme__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Schemes</relationshipLabel>
        <relationshipName>Schemes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scheme__c</fullName>
        <label>Scheme</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>of_draw_downs__c</fullName>
        <label># Of Draw Downs</label>
        <summarizedField>competitor_colors__c.of_draw_downs__c</summarizedField>
        <summaryForeignKey>competitor_colors__c.Scheme__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_Behr_QuoteToOrder_US.cls
@isTest(SeeAllData=true)
Public class Test_Behr_QuoteToOrder_US {

    static testMethod Void OpptyMultipickTest(){
        
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){
                          
             Opportunity opp = new Opportunity();
             opp= tc.insertOpportunity();
             Opportunity opp2 = new Opportunity();
             opp2 = [SELECT id, Competitors__c from Opportunity where id =: opp.id];
             Account acc = new Account();
             acc = [SELECT id,Current_Supplier__c from Account where id =: opp.AccountId];
             System.Assert((acc.Current_Supplier__c == opp2.Competitors__c),'Competitor is not same as Current Supplier');
             
             }
         test.stopTest();
         
     }
     
     static testMethod void OpptyTeamMemberTest(){
     
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){
         
             Account acc = new Account();
             acc = tc.insertParentAccount();
             
             AccountTeamMember Acctm = new AccountTeamMember();
             Acctm.AccountId = acc.ParentId;
             Acctm.UserId = UserInfo.getUserId();
             Acctm.TeamMemberRole = 'Sales Rep';
          //Acctm.AccountAccessLevel = 'Read Only';
             insert Acctm;
             
             AccountTeamMember Acctm1 = new AccountTeamMember();
             Acctm1.AccountId = acc.Id;
             Acctm1.UserId = UserInfo.getUserId();
             Acctm1.TeamMemberRole = 'Sales Rep';
          //Acctm.AccountAccessLevel = 'Read Only';
             insert Acctm1;
             
            RecordType opportunityRT = [select id, name from Recordtype where sobjectType ='Opportunity' and name = 'Opportunity'];
            Opportunity o =new Opportunity();
            o.AccountId = acc.id ;
            o.StageName = 'Position/Prepare';
            o.CloseDate = system.today() + 10;
            o.Amount = 765;
            o.Behr_Rep_Contact_Number__c = '9876543210';
            o.Behr_Rep_Email__c = 'testopp@gmail.com';
            o.Behr_Rep_Name__c = 'test rep';
            o.Name = 'test Opp';
            o.Opportunity_Type__c = 'Bid';
            o.Street__c = 'Oppty Street';
            o.City__c = 'Oppty City';
            o.State__c = 'Alabama';
            o.Zipcode__c = '123456';
            o.Country__c = 'United States';
            o.Type = 'THD';
            insert o;
            
            /*
            BEHR_QuotetoOrder_US.updateActualSales(o.AccountId);
            BEHR_QuotetoOrder_US.updateOpportunityActualSales(o.id);
            */
                        
            }
            
        Test.stopTest();
    }
    
    static testMethod void UpdateOpptyStageTest(){
    
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){
             List<Opportunity> opp = new List<Opportunity>();
             opp.add(tc.insertOpportunity());
             
            Task tasks = new Task();            
            tasks.ActivityDate = Date.today().addDays(7);
            tasks.Subject='Text Msg';
            tasks.WhatId = opp[0].Id;
            tasks.OwnerId = UserInfo.getUserId();
            tasks.Status='In Progress';
            insert tasks;
            
            Task tasksNew = new Task();            
            tasksNew.ActivityDate = Date.today().addDays(7);
            tasksNew.Subject='Job Site Visit';
            tasksNew.WhatId = opp[0].Id;
            tasksNew.OwnerId = UserInfo.getUserId();
            tasksNew.Status='In Progress';
            insert tasksNew;
            
            PricebookEntry pbe = new PricebookEntry(); 
            pbe = tc.insertPricebookEntry();
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId=opp[0].Id, PricebookEntryId=pbe.Id, Quantity = 2.0, TotalPrice = 1000.0, Zone1__c ='Off Zone');
            insert oli;
            
            BEHR_QuotetoOrder_US.UpdateOpptyStage(Opp);
            
            }
            
        Test.stopTest();
    }
    
    static testMethod void UpdateOpptyStageTest2(){
    
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){
             List<Opportunity> opp = new List<Opportunity>();
             opp.add(tc.insertOpportunity());
             
            RecordType caseRT = [select id, name from Recordtype where sobjectType ='Case' and name = 'Color Recommendation'];
            date myDate = date.today();
            date newDate = myDate.addDays(25);            
            Case nCase = new Case();                   
            nCase.Date_Needed_By__c = newDate ;
            nCase.RecordTypeId = caseRT.Id;
            nCase.Status = 'Open';
            nCase.Opportunity__c = opp[0].Id;
            insert nCase;
            
            RecordType rt1 = [select id, name from Recordtype where sobjectType ='Quote' and name = 'Order'];
            Quote q = new Quote();
            q.name = 'Q-001';
            q.recordtypeId=rt1.id;
            q.Converted_to_Order__c = true;
            q.OpportunityId = opp[0].Id;
            q.Tax = 10;
            q.ShippingHandling = 20000;  
            q.Phone = '1234567' ;
            q.ShippingState ='Arizona';
            q.Email_Address__c =  'testopp@gmail.com';  
            insert q;
            
            BEHR_QuotetoOrder_US.UpdateOpptyStage(Opp);
            
            }
            
        Test.stopTest();
    }
    
    static testMethod void cloneQuotesTest(){
    
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){
             Quote newQuote = new Quote();
             newQuote = tc.insertQuote();             
             
             PricebookEntry pbe = new PricebookEntry(); 
             pbe = tc.insertPricebookEntry();
                         
             QuoteLineItem qli = new QuoteLineItem(QuoteId = newQuote.Id, PriceBookEntryId = pbe.Id, Quantity = 1, UnitPrice = 100, Color_Vendor__c ='Benjamin Moore', Color_Name_Code1__c ='TestColor');
             insert qli; 
             
             Id cloneId = BEHR_QuotetoOrder_US.cloneQuotes(newQuote.Id);
             
             Quote cloned = new Quote();
             cloned = [SELECT id, RecordType.Name, recordtypeId, OpportunityId  from Quote where id=: cloneId];
             
             System.Assert(((cloned.recordtypeId == newQuote.recordtypeId) && (cloned.id != newQuote.id) ),'Quote is cloned properly');
             
             }
         Test.stopTest();
     }
     
     static testMethod void ConvertQuoteTest(){
     
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){
             Quote newQuote = new Quote();
             newQuote = tc.insertQuote();
             Id convertQ = BEHR_QuotetoOrder_US.ConvertQuote(newQuote.Id);
                          
             Quote order = new Quote();
             order = [SELECT id, RecordType.Name, recordtypeId, OpportunityId, Converted_to_Order__c  from Quote where id =: convertQ];
             
             System.Assert(((order.id == newQuote.id) && (order.recordtypeId != newQuote.recordtypeId) && (order.OpportunityId == newQuote.OpportunityId) && (order.Converted_to_Order__c == true)),'Quote has not been converted into order properly');
             }
         Test.stopTest();
     }
     
     static testMethod void createBookCaseTest(){
     
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){
            
            RecordType caseRT = [select id, name from Recordtype where sobjectType ='Case' and name = 'Color Book/Board'];
            date myDate = date.today();
            date newDate = myDate.addDays(25);            
            Case nCase = new Case();                   
            nCase.Date_Needed_By__c = newDate ;
            nCase.RecordTypeId = caseRT.Id;
            nCase.Color_BookBoard_Type__c = 'Color Book';
            insert nCase;
                         
             RecordType rt1 = [select id, name from Recordtype where sobjectType ='Scheme__c' and name = 'Book/Board Scheme'];
             Scheme__c sc = new Scheme__c();             
             sc.Case__c = nCase.Id;
             sc.Name = 'Test';
             sc.RecordTypeId = rt1.id ; 
             insert sc;
             
             Competitor_Color__c competitorColor = new Competitor_Color__c();
             RecordType ccRt = [select id, name from Recordtype where sobjectType ='Competitor_Color__c' and name = 'Color Only'];
             competitorColor.Name = 'Test competitor color';
             competitorColor.RecordTypeId = ccRt.Id;
             competitorColor.Color_code__c = '12';
             insert competitorColor;
             
             competitor_colors__c colorSelection = new competitor_colors__c();
             colorSelection.Competitor_Color__c = competitorColor.Id;
             colorSelection.Scheme__c = sc.Id;
             colorSelection.of_draw_downs__c = 1;
             insert colorSelection;
             
             Date dateneeded = Date.TODAY();
             date nDate = dateneeded.addDays(4);
             
             Id bkCaseid = BEHR_QuotetoOrder_US.CreateBookCase(sc.id);
             
             Case createdC = new case();
             createdC = [SELECT RecordTypeId, Color_BookBoard_Type__c, Date_Needed_By__c from Case where id =: bkCaseid];
             
             System.Assert((createdC.RecordTypeId == nCase.RecordTypeId && createdC.Color_BookBoard_Type__c == nCase.Color_BookBoard_Type__c && createdC.Date_Needed_By__c == nDate),'Case created is not the same as source(BOOK/BOARD) case.');
             
             }
         Test.stopTest();
     }
     
     static testMethod void createBoardCaseTest(){
     
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){
            
            RecordType caseRT = [select id, name from Recordtype where sobjectType ='Case' and name = 'Color Book/Board'];
            date myDate = date.today();
            date newDate = myDate.addDays(25);            
            Case nCase = new Case();                   
            nCase.Date_Needed_By__c = newDate ;
            nCase.RecordTypeId = caseRT.Id;
            nCase.Color_BookBoard_Type__c = 'Color Board';
            insert nCase;
                         
             RecordType rt1 = [select id, name from Recordtype where sobjectType ='Scheme__c' and name = 'Book/Board Scheme'];
             Scheme__c sc = new Scheme__c();             
             sc.Case__c = nCase.Id;
             sc.Name = 'Test';
             sc.RecordTypeId = rt1.id ; 
             insert sc;
             
             Competitor_Color__c competitorColor = new Competitor_Color__c();
             RecordType ccRt = [select id, name from Recordtype where sobjectType ='Competitor_Color__c' and name = 'Color Only'];
             competitorColor.Name = 'Test competitor color';
             competitorColor.RecordTypeId = ccRt.Id;
             competitorColor.Color_code__c = '12';
             insert competitorColor;
             
             competitor_colors__c colorSelection = new competitor_colors__c();
             colorSelection.Competitor_Color__c = competitorColor.Id;
             colorSelection.Scheme__c = sc.Id;
             colorSelection.of_draw_downs__c = 1;
             insert colorSelection;
             
             Date dateneeded = Date.TODAY();
             date nDate = dateneeded.addDays(14);
             
             Id bkCaseid = BEHR_QuotetoOrder_US.CreateBookCase(sc.id);
             
             Case createdC = new case();
             createdC = [SELECT RecordTypeId, Color_BookBoard_Type__c, Date_Needed_By__c from Case where id =: bkCaseid];
             
             System.Assert((createdC.RecordTypeId == nCase.RecordTypeId && createdC.Color_BookBoard_Type__c == nCase.Color_BookBoard_Type__c && createdC.Date_Needed_By__c == nDate),'Case created is not the same as source(BOOK/BOARD) case.');
             
             }
         Test.stopTest();
     }
     
     
     static testMethod void CreateDigitalRenderingTest(){
     
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){
             
             RecordType caseRT = [select id, name from Recordtype where sobjectType ='Case' and name = 'Digital Renderings'];
            date myDate = date.today();
            date newDate = myDate.addDays(25);            
            Case nCase = new Case();                   
            nCase.Date_Needed_By__c = newDate ;
            nCase.RecordTypeId = caseRT.Id;
            insert nCase;
                        
            RecordType rt1 = [select id, name from Recordtype where sobjectType ='Scheme__c' and name = 'Digital Rendering Scheme'];
             Scheme__c sc = new Scheme__c();             
             sc.Case__c = nCase.Id;
             sc.Name = 'Test';
             sc.RecordTypeId = rt1.id ; 
             insert sc;
             
             Competitor_Color__c competitorColor = new Competitor_Color__c();
             RecordType ccRt = [select id, name from Recordtype where sobjectType ='Competitor_Color__c' and name = 'Color Only'];
             competitorColor.Name = 'Test competitor color';
             competitorColor.RecordTypeId = ccRt.Id;
             competitorColor.Color_code__c = '12';
             insert competitorColor;
             
             competitor_colors__c colorSelection = new competitor_colors__c();
             colorSelection.Competitor_Color__c = competitorColor.Id;
             colorSelection.Scheme__c = sc.Id;
             colorSelection.of_draw_downs__c = 1;
             insert colorSelection;
             
             Date dateneeded = Date.TODAY();
             date nDate = dateneeded.addDays(3);
             
             Id bkCaseid = BEHR_QuotetoOrder_US.CreateDigitalRendering(sc.Id);
             
             Case createdC = new case();
             createdC = [SELECT RecordTypeId, Color_BookBoard_Type__c, Date_Needed_By__c from Case where id =: bkCaseid];
             
             System.Assert((createdC.RecordTypeId == nCase.RecordTypeId && createdC.Date_Needed_By__c == nDate),'Case created is not the same as source(DIGITAl RENDERING) case.');
             
             }
         Test.stopTest();
     }
     
     static testMethod void createDrawDownsTest(){
     
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){
         
             RecordType caseRT = [select id, name from Recordtype where sobjectType ='Case' and name = 'Draw Downs'];
            date myDate = date.today();
            date newDate = myDate.addDays(25);            
            Case nCase = new Case();                   
            nCase.Date_Needed_By__c = newDate ;
            nCase.RecordTypeId = caseRT.Id;
            insert nCase;
                        
            RecordType rt1 = [select id, name from Recordtype where sobjectType ='Scheme__c' and name = 'Draw Down Scheme'];
             Scheme__c sc = new Scheme__c();             
             sc.Case__c = nCase.Id;
             sc.Name = 'Test';
             sc.RecordTypeId = rt1.id ; 
             insert sc;
             
             Competitor_Color__c competitorColor = new Competitor_Color__c();
             RecordType ccRt = [select id, name from Recordtype where sobjectType ='Competitor_Color__c' and name = 'Color Only'];
             competitorColor.Name = 'Test competitor color';
             competitorColor.RecordTypeId = ccRt.Id;
             competitorColor.Color_code__c = '12';
             insert competitorColor;
             
             competitor_colors__c colorSelection = new competitor_colors__c();
             colorSelection.Competitor_Color__c = competitorColor.Id;
             colorSelection.Scheme__c = sc.Id;
             colorSelection.of_draw_downs__c = 1;
             insert colorSelection;
             
             Date dateneeded = Date.TODAY();
             date nDate = dateneeded.addDays(3);
             
             Id bkCaseid = BEHR_QuotetoOrder_US.CreateDrawDowns(sc.Id);
             
             Case createdC = new case();
             createdC = [SELECT RecordTypeId, Color_BookBoard_Type__c, Date_Needed_By__c from Case where id =: bkCaseid];
             
             System.Assert((createdC.RecordTypeId == nCase.RecordTypeId && createdC.Date_Needed_By__c == nDate),'Case created is not the same as source(DIGITAl RENDERING) case.');
             
             }
         Test.stopTest();
     }
     
     static testMethod void SendTestEmail1Test(){
         
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){         
         
             String email = 'testuser@sfdc.com';
             String documentname = 'Credit Application Form';
             BEHR_QuotetoOrder_US.SendTestEmail1(email,documentname);
             
             }
             
         Test.stopTest();
     }
     
     static testMethod void updateQuoteLineItemsTest(){
         
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){
             Quote newQuote = new Quote();
             newQuote = tc.insertQuote();             
             
             PricebookEntry pbe = new PricebookEntry(); 
             pbe = tc.insertPricebookEntry();
                         
             QuoteLineItem qli = new QuoteLineItem(QuoteId = newQuote.Id, PriceBookEntryId = pbe.Id, Quantity = 1, UnitPrice = 100, Color_Vendor__c ='Benjamin Moore', Color_Name_Code1__c ='TestColor');
             insert qli;             
         
         /** Testing the auto update of the Color Vendor and Color Brand in quote line item from the color for orders records **/
             Competitor_Color__c competition = new Competitor_Color__c();
             competition.Color_Brand__c = 'Behr';
             competition.Color_code__c = 'testXYZ';
             competition.Color_Name__c = 'Bright Morning';
             insert competition;
             
             Color_for_orders__c colorForOrder = new Color_for_orders__c();
             colorForOrder.Competitor_Color__c = competition.Id;
             colorForOrder.Quote_Line_Item__c = qli.Id;
             insert colorForOrder;
             
             delete colorForOrder;
         /** End of the auto update of color vendor and color brand **/            
             
             }
             
         Test.stopTest();
     }
     
     static testMethod void updateAccountZoneTest(){
         
         Test.startTest();        
         Test_Utility_BehrClass tc = new Test_Utility_BehrClass();
         User u = new user();
         u = tc.insertUser();
         
         System.runAs(u){             
                      
         /** Testing for updation of Account ZONE update when Direct Onboarding Record is updated Scenario test **/
             Direct_Onboarding__c DirOnb = new Direct_Onboarding__c();     
             DirOnb = tc.insertDirectOnboarding();             
             
             DirOnb.Description__c = ' A new account being onboarded for update ';
             DirOnb.Status__c = 'Pending Credit Review';            
             update DirOnb;
         /** END OF updation of ACCOUNT ZONE UPDATE when Direct Onboarding Record is updated **/
                   
             
             }
             
         Test.stopTest();
     }
     
        
         
}