src/objects/Behr_Custom_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Information__c</fullName>
        <label>Information</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Behr Custom Settings</label>
</CustomObject>

src/objects/Home_Depot_Store__c.object
<CustomObject>
    <description>Details of the Home Depot Store selling BEHR products</description>
    <label>THD Stores</label>
    <nameField>
        <label>THD Store Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>THD Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>THD_Store__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Home Depot Store involved in this opportunity</description>
        <label>THD Store</label>
        <referenceTo>Home_Depot_Store__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity Sales Process</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Order_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pro_Rewards__c</fullName>
        <formula>Account__r.Pro_Rewards_Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pro Rewards #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rep_Email__c</fullName>
        <formula>CreatedBy.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rep Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rep_Name__c</fullName>
        <formula>CreatedBy.FirstName +&apos; &apos; +  CreatedBy.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rep Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rep_Phone__c</fullName>
        <formula>CreatedBy.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rep Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_Delivery_Date__c</fullName>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sent_To_HD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent To HD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ship_To_Name_PDF__c</fullName>
        <formula>ShippingName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ship To Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Instructions__c</fullName>
        <label>Special Instructions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>THD_Store__c</fullName>
        <formula>HYPERLINK(&quot;https://na5.salesforce.com/&quot;&amp; Opportunity.THD_Store__c, Opportunity.THD_Store__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>THD Store</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_Of_Order__c</fullName>
        <label>Type Of Order</label>
        <picklist>
            <picklistValues>
                <fullName>Direct to store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct to site</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <description>Provide users with the ability to place orders in Salesforce.These orders will then be distributed to other systems to allow easier order entry.</description>
        <label>Order</label>
    </recordTypes>
    <recordTypes>
        <fullName>Quote</fullName>
        <active>true</active>
        <label>Quote</label>
    </recordTypes>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Base__c</fullName>
        <formula>Product2.Base__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Name_Code1__c</fullName>
        <label>Color Name/Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Vendor__c</fullName>
        <label>Color Vendor</label>
        <picklist>
            <picklistValues>
                <fullName>Behr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn-Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Tint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_ID__c</fullName>
        <formula>IF(ISPICKVAL( Color_Vendor__c ,&apos;No Tint&apos;) ,  PricebookEntry.Product2.ProductCode ,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sheen__c</fullName>
        <formula>TEXT(Product2.Sheen__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sheen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <formula>Product2.Size__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Size</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use__c</fullName>
        <formula>TEXT(Product2.Use__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Use</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <formula>Product2.Vendor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/SendtoHDController.cls
/*Class Name: SendtoHDController 
@Author Name: Prasanna C
@Purpose: This class has method to send Mail to HD on Send to HD button on Order Layout
@Created Date: 2/12/2014
@Last modified by: Prasanna
@Last modified date: 4/12/2014 */
/*** Apex class written to send mail to a static email with attachment***/
public class SendtoHDController {
    public String pdfName;
    Blob body;  
    public Quote quoteSource {get;set;}
    public List<QuoteLineItem> quoteLineItems {get; set;}    
    /*** Constructor method for this Apex class ***/
    public SendtoHDController(ApexPages.StandardController controller) {
      //  this.quoteSource = (quote)controller.getRecord();
        Id quoteId = ApexPages.CurrentPage().getParameters().get('id'); 
        SObject[] quoteTemp = [SELECT id, QuoteNumber,Rep_Name__c,Rep_Phone__c, Rep_Email__c, Order_Date__c, Type_Of_Order__c, Opportunity.THD_Store__r.Name,
                                 Account.name, Pro_Rewards__c, Project_Name__c, Opportunity.Primary_Contact__r.Name, Phone, Email, Special_Instructions__c,
                                 Requested_Delivery_Date__c, Name, CreatedBy.name,Ship_To_Name_PDF__c, ShippingStreet,ShippingCity,ShippingState,ShippingPostalCode,ShippingCountry,  
                                 (SELECT Id, Vendor__c,Use__c,Sheen__c, Base__c, Product__c, Product_ID__c, Color_Vendor__c, Color_Name_Code1__c,Size__c,Quantity FROM QuoteLineItems)
                                 FROM Quote WHERE id = :quoteId LIMIT 1];
        quoteLineItems = new List<QuoteLineItem>();
        List<Quote> quoteListTemp = (List<Quote>) quoteTemp;
        quoteSource = quoteListTemp[0];
        quoteLineItems = (List<QuoteLineItem>) quoteTemp.get(0).getSObjects('QuoteLineItems');
      
    }
    /*** Method to send email to static mail id with the visualforce template attachment***/
    public pagereference sendEmail() {  
        PageReference thePDF;  
        quoteSource.Sent_To_HD__c = True;
        PageReference acctPage;
        try{
            Database.update(quoteSource);
        }
        catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        
       
        try{
            thePDF = Page.SenttoHD;
            thePDF.getParameters().put('id',quoteSource.Id);
            pdfName = 'SendToHD'+' '+System.Now()+ '.'+ 'pdf';
            try{
               body = thePDF.getContentAsPDF();
            }catch (VisualforceException e) {
               body = Blob.valueOf('PDF error');
            }
        
            //Accessing Email id from 'Behr_Custom_Settings__c' Custom Setting
            Behr_Custom_Settings__c sendEmailId= Behr_Custom_Settings__c.getValues(Label.SendHD_Custom_Setting);
            String hdEmail = sendEmailId.Information__c;       
            
            EmailTemplate templateId = [Select id,name from EmailTemplate where name =: Label.HD_Order_Email_Template limit 5];
            if(templateId != Null){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new String[] {hdEmail});
                mail.setTargetObjectId(UserInfo.getUserId());
                mail.setTemplateId(templateId.id);
                mail.setWhatId(quoteSource.Id);
                mail.setSaveAsActivity(false);
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
            }
            acctPage = new ApexPages.StandardController(quoteSource).view();
            acctPage.setRedirect(true);
            
            Attachment attach = new Attachment();
            attach.Body = body;
            attach.Name = pdfName;
            attach.IsPrivate = false;
            attach.ParentId = quoteSource.Id;
            insert attach;
          
        }
        Catch(Exception e){
              System.debug('The following exception has occurred: ' + e.getMessage());
        }
        return acctPage;
    }
    /*** Method to cancel the action and return to the previous order record***/
    public pagereference cancel() {
        PageReference acctPage;
        try{
            acctPage = new ApexPages.StandardController(quoteSource).view();
            acctPage.setRedirect(true);
        }
        Catch(Exception e){
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        return acctPage;
    }

}