src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Services_Requested__c</fullName>
        <label>Services Requested</label>
        <picklist>
            <picklistValues>
                <fullName>Color Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery/Factory Tinting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Express Store Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Site Visits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terms/Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Services(s) Not Listed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None Requested</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <label>Sub-Lead Source</label>
        <picklist>
            <controllingField>LeadSource</controllingField>
            <picklistValues>
                <fullName>Contractor Trade Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THD Pro Blitz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Rep Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DTP Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Magazine Publication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web to Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BehrPro Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PASA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>See Trade Association/Affiliation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store Walk In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Behr_Rep_Contact__c</fullName>
        <description>Customer would like for a Behr Rep to contact them</description>
        <inlineHelpText>Indicates if the customer would like  a Behr Rep to contact them</inlineHelpText>
        <label>Behr Rep Contact</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Monthly_Paint_Usage__c</fullName>
        <label>Estimated Monthly Paint Usage</label>
        <picklist>
            <picklistValues>
                <fullName>&lt;50 Gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51-124 Gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;125 Gallons</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Over 45 gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;124 Gallons</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Profession/Market Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B2B(OEM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exporter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Painting and Wall Covering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remodeler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifier</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Expected_Paint_Purchase__c</fullName>
        <inlineHelpText>Question Related to Architect, Designer, General Contractor, Remodeler</inlineHelpText>
        <label>Next Expected Paint Purchase</label>
        <picklist>
            <controllingField>Have_Upcoming_Projects__c</controllingField>
            <picklistValues>
                <fullName>&lt;90 Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 to 6 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;6 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nothing Planned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Brands__c</fullName>
        <label>Preferred Brands</label>
        <picklist>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex (Frazee/Kwal/Color Wheel/Parker)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn-Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly-Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG (Olympic/Pittsburg/Porter)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin-Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valspar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <picklist>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both Spanish and English</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pro_Rewards_Account_Number__c</fullName>
        <inlineHelpText>Number set up in Pro Rewards (can differ from contact number)</inlineHelpText>
        <label>Pro Rewards Account Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Services_Requested__c</fullName>
        <label>Services Requested</label>
        <picklist>
            <picklistValues>
                <fullName>Color Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery/Factory Tinting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Express Store Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Site Visits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terms/Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Services(s) Not Listed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None Requested</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Sub_Lead_Source__c</fullName>
        <description>Sub lead source</description>
        <label>Sub-Lead Source</label>
        <picklist>
            <controllingField>LeadSource</controllingField>
            <picklistValues>
                <fullName>Contractor Trade Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THD Pro Blitz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Rep Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DTP Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Magazine Publication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web to Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BehrPro Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PASA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>See Trade Association/Affiliation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store Walk In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WOD_Active_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the LEAD has a Web on Demand active account</description>
        <inlineHelpText>Indicates if the lead has a Web Enabled Business or Web on Demand account</inlineHelpText>
        <label>WEB Active User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WOD_Address__c</fullName>
        <description>Indicates the Web on Demand address for the lead</description>
        <inlineHelpText>Indicates the Web on Demand address for the lead</inlineHelpText>
        <label>WEB Address</label>
        <type>Url</type>
    </fields>
</CustomObject>

src/classes/ProRegistrationSync.cls
global class ProRegistrationSync {
    
    
    webService static String saveProContactInfo(Lead lead) {
        
        String id = '';
        
        try { 
                lead.LeadSource = 'Marketing';
                lead.Sub_Lead_Source__c = 'BehrPro Website';
                lead.RecordTypeId = '012700000001Y7s'; //Standard Leads
                
                Database.SaveResult leadSaveResult = Database.Insert(lead, false);
                
                id = leadSaveResult.getId();
                
                Database.Error[] errsLead = leadSaveResult.getErrors();
                for(Database.Error err : errsLead)
                    System.debug(err.getStatusCode() + ' - ' + err.getMessage());
                
                /*
                Database.SaveResult contactSaveResult = Database.Insert(contact, false);
                                        
                Database.Error[] errsContact = contactSaveResult.getErrors();
                for(Database.Error err : errsContact)
                    System.debug(err.getStatusCode() + ' - ' + err.getMessage());
                    */                    
                } catch (Exception e) {
                    System.debug(e.getTypeName() + ' - ' + e.getCause() + ': ' + e.getMessage());
                }
        
        return id;
            }
           
    webService static String updateProContactInfo(Lead lead) {
        
        String id = '';
        
        try { 
                Lead existingLead = [SELECT Company, Phone, FirstName, LastName, 
                 Services_Requested__c, Estimated_Monthly_Paint_Usage__c, Next_Expected_Paint_Purchase__c,
                 Preferred_Brands__c, Behr_Rep_Contact__c, Street, City, State, PostalCode, Market_Segment__c, 
                 HasOptedOutOfEmail, WOD_Active_User__c, WOD_Address__c, 
                 Preferred_Language__c, Pro_Rewards_Account_Number__c, 
                 Website  FROM Lead
                 WHERE Email = :lead.Email LIMIT 1];
                                 
                //lead.Company = existingLead.Company;
                if (existingLead == NULL) {
                    saveProContactInfo(lead);
                } else {
                    existingLead.Company = lead.Company;
                    existingLead.Phone = lead.Phone;
                    existingLead.FirstName = lead.FirstName;
                    existingLead.LastName = lead.LastName;
                    existingLead.Services_Requested__c = lead.Services_Requested__c;
                    existingLead.Estimated_Monthly_Paint_Usage__c = lead.Estimated_Monthly_Paint_Usage__c;
                    existingLead.Next_Expected_Paint_Purchase__c = lead.Next_Expected_Paint_Purchase__c;
                    if (lead.Behr_Rep_Contact__c == 'NoChange'){
                        //do nothing
                    } else {
                        existingLead.Behr_Rep_Contact__c = lead.Behr_Rep_Contact__c;
                    }                
                    existingLead.Street = lead.Street;
                    existingLead.City = lead.City;
                    existingLead.State = lead.State;
                    existingLead.PostalCode = lead.PostalCode;                
                    existingLead.Market_Segment__c = lead.Market_Segment__c;
                    existingLead.HasOptedOutOfEmail = lead.HasOptedOutOfEmail;
                    existingLead.WOD_Active_User__c = lead.WOD_Active_User__c;
                    existingLead.WOD_Address__c = lead.WOD_Address__c;
                    
                    existingLead.Preferred_Language__c = lead.Preferred_Language__c;
                    existingLead.Pro_Rewards_Account_Number__c = lead.Pro_Rewards_Account_Number__c;
                    
                    existingLead.Preferred_Brands__c = lead.Preferred_Brands__c;
                    
                    //existingLead.Website = lead.Website;
                    
                    update existingLead;     
                }
                
                        
                                  
                } catch (Exception e) {
                    System.debug(e.getTypeName() + ' - ' + e.getCause() + ': ' + e.getMessage());
                }
        
        return id;
            }
}