src/objects/Home_Depot_Store__c.object
<CustomObject>
    <description>Details of the Home Depot Store selling BEHR products</description>
    <fields>
        <fullName>RPSM__c</fullName>
        <label>RPSM</label>
        <picklist>
            <picklistValues>
                <fullName>Abe Suleiman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Mahoney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brandon Jones</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brian Emmert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermot McGuire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greg Goodwin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>John Wysor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luke Markes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Randy Rivers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spyros Zorbas</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Rep_Email__c</fullName>
        <description>In Store Rep Email</description>
        <label>Store Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>THD Stores</label>
    <nameField>
        <label>THD Store Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>THD Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Estimated_Monthly_Paint_Usage__c</fullName>
        <label>Estimated Monthly Paint Usage</label>
        <picklist>
            <picklistValues>
                <fullName>&lt;50 Gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51-124 Gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;125 Gallons</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Over 45 gallons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;124 Gallons</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Store_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Store #</label>
        <referenceTo>Home_Depot_Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RPSM__c</fullName>
        <formula>Owner:User.RPSM_New__r.FirstName &amp; &quot; &quot; &amp; Owner:User.RPSM_New__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RPSM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code_lookup_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip Code lookup</label>
        <referenceTo>Zip_Code_Assignment__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads_del</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>RPSM__c</fullName>
        <description>Regional Pro Sales Manager</description>
        <label>RPSM Old</label>
        <picklist>
            <picklistValues>
                <fullName>Abe Suleiman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Mahoney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brandon Jones</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brian Emmert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermot McGuire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greg Goodwin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>John Wysor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luke Markes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mike Marienthal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neal Sherman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phillip Hayes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Randy Rivers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spyros Zorbas</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Zip_Code_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>The zip code that will be matched against for assignment logic.</description>
        <externalId>true</externalId>
        <inlineHelpText>The zip code that will be matched against for assignment logic.</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Zip Code Assignment</label>
    <nameField>
        <label>Zip Code Mappings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_Behr_UpdateLeadStatus.cls
@isTest (Seealldata = true)
private class Test_Behr_UpdateLeadStatus{
    Static testmethod void testtrigger(){
    
        Profile p=[SELECT Id FROM profile WHERE name='Standard User Level 2'];
        Profile p1=[SELECT Id FROM profile WHERE name='System Administrator'];

        UserRole ur=new UserRole(Name='Behr Pro Rep'); 
        User u1=new User(alias = 'proxy456', 
        email='proxy@proxy456.com',emailencodingkey='UTF-8', lastname='proxy456',
        languagelocalekey='en_US',localesidkey='en_US',
        rpsm__c='test',
        UserRoleid=ur.id,
        profileid = p.Id,timezonesidkey='America/Los_Angeles',username='proxy@proxy456.com',CommunityNickname='proxy456.aaa');
        insert u1; 
  
  User u2=new User(alias = 'Behr', 
        email='proxy@proxy456.com',emailencodingkey='UTF-8', lastname='Behr Instore Rep',
        languagelocalekey='en_US',localesidkey='en_US',
        rpsm__c='test',
        UserRoleid=ur.id,
        profileid = p1.Id,timezonesidkey='America/Los_Angeles',username='abc@proxy456.com',CommunityNickname='proxy456.bbb');
        insert u2; 
    
system.runas(u2){
         Zip_Code_Assignment__c zca = new Zip_Code_Assignment__c(Zip_code__c='123458');
        insert zca;
        //Group g = new Group (name='Pro Unassigned',Type='Queue');
        //insert g;
        Home_Depot_Store__c hdt = new Home_Depot_Store__c(OWNERID=u1.id,NAME='6788888',STORE_REP_EMAIL__C='abc@gmail.com');
        insert hdt; 
        Lead l = new Lead(Company='Test',FirstName='Trigger',LastName='Test',Phone='98746513',Email='asd@as.com',PostalCode='123458' , Primary_Store_Number__c =hdt.id,  Zip_Code_lookup_del__c = zca.id,Estimated_Monthly_Paint_Usage__c='>125 Gallons',Status = 'Unqualified');
        insert l;
        l.Postalcode=null;
  
          update l;    
          List<Group> queueList = [select Id from Group where Name = 'Pro Unassigned' and Type = 'Queue'];
          id unAssignedProLeadId = null;
          if (queueList.size() >=0 )
          {
              unAssignedProLeadId = queueList[0].id;
          }
          l = new Lead(Company='Test',FirstName='Trigger',LastName='Test',Phone='98746513',Email='asd@as.com',OwnerId=unAssignedProLeadId);
        insert l;
        //l.PostalCode='123456';
        //update l;
        Task t = new Task(WhoId=l.Id,Subject='Test',ActivityDate=Date.Today(),Status='In Progress',Update_Lead_Status__c='contact made',Priority='Normal');
        insert t;
        }
  
  }      
  //l = [SELECT Id,First_Activity_Date__c FROM Lead WHERE Id = :l.Id];
        //System.assertEquals(t.ActivityDate,l.First_Activity_Date__c);
        
}