src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Behr_Rep_Contact_Number__c</fullName>
        <inlineHelpText>Phone number customer can reach you</inlineHelpText>
        <label>Behr Rep Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Behr_Rep_Email__c</fullName>
        <label>Behr Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Behr_Rep_Name__c</fullName>
        <label>Behr Rep Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_per_Gallon__c</fullName>
        <label>Price Per Gallon</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>Opportunity Sales Process</businessProcess>
        <label>Opportunity</label>
    </recordTypes>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes/Orders</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Convert_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Convert to Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Converted_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted to Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_per_Gallon__c</fullName>
        <label>Price per Gallon</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Quote</fullName>
        <active>true</active>
        <label>Quote</label>
    </recordTypes>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Base__c</fullName>
        <formula>Product2.Base__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Name_Code1__c</fullName>
        <label>Color Name/Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Name_Code__c</fullName>
        <label>Color Name/Code</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Vendor__c</fullName>
        <label>Color Vendor</label>
        <picklist>
            <picklistValues>
                <fullName>Behr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn-Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Tint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant1__c</fullName>
        <label>Colorant 2</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant2__c</fullName>
        <label>Colorant 3</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant3__c</fullName>
        <label>Colorant 4</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant4__c</fullName>
        <label>Colorant 5</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant__c</fullName>
        <label>Colorant 1</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OZ_1__c</fullName>
        <label>OZ 1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_2__c</fullName>
        <label>OZ 2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_3__c</fullName>
        <label>OZ 3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_4__c</fullName>
        <label>OZ 4</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_5__c</fullName>
        <label>OZ 5</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_per_Gallon__c</fullName>
        <formula>Your_Price__c / ( VALUE( Product2.Size__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price per Gallon</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sheen__c</fullName>
        <formula>TEXT(Product2.Sheen__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sheen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <formula>Product2.Size__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Size</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use__c</fullName>
        <formula>TEXT(Product2.Use__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Use</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <formula>Product2.Vendor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X384ths_1__c</fullName>
        <label>384ths 1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_2__c</fullName>
        <label>384ths 2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_3__c</fullName>
        <label>384ths 3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_4__c</fullName>
        <label>384ths 4</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_5__c</fullName>
        <label>384ths 5</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Your_Price__c</fullName>
        <formula>UnitPrice * (1 - Discount)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Your Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/BEHR_QuoteClone_US.cls
Global class BEHR_QuoteClone_US {
    public BEHR_QuoteClone_US (){
    }
  public static string getCreatableFieldsSOQL(String objectName, String whereClause){
 
        String selects = '';
 
        if (whereClause == null || whereClause == ''){ return null; }
 
        // Get a map of field name and field token
        Map<String, Schema.SObjectField> fMap = Schema.getGlobalDescribe().get(objectName.toLowerCase()).getDescribe().Fields.getMap();
        list<string> selectFields = new list<string>();
 
        if (fMap != null){
            for (Schema.SObjectField ft : fMap.values()){ // loop through all field tokens (ft)
                Schema.DescribeFieldResult fd = ft.getDescribe(); // describe each field (fd)
                if (fd.isCreateable()){ // field is creatable
                    selectFields.add(fd.getName());
                }
            }
        }
 
        if (!selectFields.isEmpty()){
            for (string s:selectFields){
                selects += s + ',';
            }
            if (selects.endsWith(',')){selects = selects.substring(0,selects.lastIndexOf(','));}
 
        }
 
        return 'SELECT ' + selects + ' FROM ' + objectName + ' WHERE ' + whereClause;
 
    } 
   
    
   webservice static Id cloneQuote(id qid){
   List<QuoteLineItem> qlilst = new List<QuoteLineItem>();
   List<QuoteLineItem> qliolst = new List<QuoteLineItem>();
   //system.debug('@@@@@@@'+qid);
   String quoteid=(String)qid;
   List<Quote> qlst = new List<Quote>();
  
   string o='id=\''+qid+'\'';  
    string o1='id=\''+qid+'\'';
  string id;
  system.debug('check2222'+o1);
  string p='\'a\'';
 
  
  qlst= [select Account__c,RecordtypeID,OpportunityID ,name from Quote where id=:qid];
  Opportunity Op1=[select StageName ,Closedate ,Behr_Rep_Name__c,Behr_Rep_Email__c,
                       Behr_Rep_Contact_Number__c,RecordTypeId,Opportunity_Type__c from 
                           Opportunity where id=:qlst[0].OpportunityId];
    Account acc=[select name from Account where id =:qlst[0].Account__c]; 
  
                               
   list<RecordType> rt1=[SELECT r.Id, r.Name, r.SobjectType 
                 FROM RecordType r 
                 WHERE SobjectType='Opportunity' AND r.Name='Opportunity For Quote' limit 1]; 
  
  
  Opportunity Op = new Opportunity(AccountId = qlst[0].Account__c , StageName = op1.StageName  ,
                                        Closedate = op1.Closedate  , Name = acc.name+'_'+System.Now().format('MM/dd/yy HH:mm a', 'PST'),
 
                                        Behr_Rep_Name__c =op1.Behr_Rep_Name__c ,Behr_Rep_Email__c=op1.Behr_Rep_Email__c ,
                                        Behr_Rep_Contact_Number__c =op1.Behr_Rep_Contact_Number__c ,
                                        RecordTypeId=op1.RecordTypeId,Opportunity_Type__c=op1.Opportunity_Type__c);
  insert op;
  
  
  
    String soql = getCreatableFieldsSOQL('Quote',o);
 
    Quote q = (Quote)Database.query(soql);
    Quote q2 = q.clone(false, true);
    q2.OpportunityId=op.id;
    insert q2;
    
     qlilst = [SELECT Your_Price__c, Vendor__c, Use__c, UnitPrice, TotalPrice, Subtotal, SortOrder,
                  Size__c, Sheen__c, QuoteId, Quantity, PricebookEntryId, Price_per_Gallon__c, ListPrice,
                  LineNumber, Discount, Description, Color_Vendor__c, Color_Name_Code__c, Base__c,
                  X384ths_1__c, X384ths_2__c, X384ths_3__c, X384ths_4__c, X384ths_5__c,
                  Colorant__c, Colorant1__c, Colorant2__c, Colorant3__c, Colorant4__c,
                  Color_Name_Code1__c,
                  OZ_1__c, OZ_2__c, OZ_3__c, OZ_4__c, OZ_5__c 
                  FROM QuoteLineItem 
                  WHERE QuoteId =: q.id];
      system.debug('LLLLLLLLLLLLL'+qlilst) ;           
         
        for(Quotelineitem qli : qlilst){
           Quotelineitem insertqli;           
           insertqli = qli.clone(false,true);
           insertqli.QuoteId = q2.id;          
           qliolst.add(insertqli); 
           system.debug('qliiiiiiiiiiiii'+qliolst);
        } 
        insert qliolst;  
    
   
    
    q2.name=acc.name+'_'+System.Now().format('MM/dd/yy HH:mm a', 'PST');
    
    q2.Converted_to_Order__c=false;
    q2.Convert_to_Order__c=false;
   
    update q2;
    
    
         system.debug('OOOOOOOOOOOOOO'+qlilst) ;             
    return q2.id;
  
    
    }
    
 

}