src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Base__c</fullName>
        <label>Base</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sheen__c</fullName>
        <label>Sheen</label>
        <picklist>
            <picklistValues>
                <fullName>Barn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basement/Masonry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete/Masonry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead Flat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deck/Fence/Siding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decorative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eggshell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elastomeric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Epoxy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat/Matte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat Enamel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gloss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gloss Enamel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gloss Porch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Log Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Porch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primers 02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Satin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Gloss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Transparent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Transparent Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solid Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transparent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <description>Gallonage</description>
        <label>Size</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use__c</fullName>
        <label>Use</label>
        <picklist>
            <picklistValues>
                <fullName>Interior Paint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exterior Paint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior/Exterior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exterior Stains/Water Sealers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Proofers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Textures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Base__c</fullName>
        <formula>Product2.Base__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Name_Code__c</fullName>
        <label>Color Name/Code</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Vendor__c</fullName>
        <label>Color Vendor</label>
        <picklist>
            <picklistValues>
                <fullName>Behr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn-Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Tint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant1__c</fullName>
        <label>Colorant 2</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant2__c</fullName>
        <label>Colorant 3</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant__c</fullName>
        <label>Colorant 1</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OZ_1__c</fullName>
        <label>OZ 1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_2__c</fullName>
        <label>OZ 2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_3__c</fullName>
        <label>OZ 3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_4__c</fullName>
        <label>OZ 4</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_5__c</fullName>
        <label>OZ 5</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sheen__c</fullName>
        <formula>TEXT(Product2.Sheen__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sheen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <formula>Product2.Size__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Size</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use__c</fullName>
        <formula>TEXT(Product2.Use__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Use</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <formula>Product2.Vendor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X384ths_1__c</fullName>
        <label>384ths 1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_2__c</fullName>
        <label>384ths 2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_3__c</fullName>
        <label>384ths 3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_4__c</fullName>
        <label>384ths 4</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_5__c</fullName>
        <label>384ths 5</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/Behr_orderLineItemEdit.cls
public class Behr_orderLineItemEdit {
 public string product{get;set;}
 public Boolean disableInput {get; set;}
  public Boolean dummydisableInput {get; set;}
 public QuoteLineitem qliobj{get;set;}
 public String colorvendor{get; set;}
 public Boolean flag{get;set;}
    public Behr_orderLineItemEdit(ApexPages.StandardController controller) {
    flag=false;
    disableInput=true;
        qliobj =[select quoteId,ListPrice,Quantity,Color_Vendor__c,Color_Name_Code__c,Use__c, Sheen__c, Base__c, Vendor__c, Size__c,
                 X384ths_5__c, X384ths_4__c, X384ths_3__c, X384ths_2__c, X384ths_1__c, OZ_5__c, OZ_4__c, OZ_3__c, OZ_2__c, 
                 OZ_1__c, Colorant__c,Colorant1__c,Colorant2__c,Colorant3__c,Colorant4__c, Unitprice, Discount from QuoteLineItem 
                 where id=:controller.getRecord().id];
                 if(qliobj.Color_Vendor__c=='Color Formula')
                    flag =true;
        
    }
    
    public void onchange1(){
        
        if(qliobj.Color_Vendor__c=='Color Formula')
        {
            flag =true;
            disableInput=false;
            dummydisableInput =true;
            }
        else 
        {
          flag =false;
           disableInput=true;
           dummydisableInput =false;
           }
        system.debug('onchangeeeeeeeeeeeee'+flag);
       // return null;
        }
    
    public pagereference redirect(){
    string qliid,returl,rt1;
    qliid=ApexPages.currentPage().getParameters().get('id');
    returl=ApexPages.currentPage().getParameters().get('retURL');
     rt1=retURL.substring(1,(retURL.length()));
    List<QuoteLineitem> QLI=[select id, PricebookEntryId,QuoteId from QuoteLineitem where id=:qliid];
    system.debug('IIIIIIIIIIIIIIII'+QLI[0].PricebookEntryId );
    PricebookEntry  pbe=[select Product2Id from PricebookEntry where id =:QLI[0].PricebookEntryId ];
    system.debug('AAAAAAAAAAAAAAAA'+pbe.Product2Id );
    Product2 pro=[select id,Name from Product2 where id =:pbe.Product2Id ];
    system.debug('SSSSSSSSSSSSSSSSS'+pro.Name);
    Quote q=[select id,recordtypeid,Converted_to_Order__c from Quote where id=:QLI[0].QuoteId ];
    product=pro.Name;
   return null;
    
    }
    public pagereference save1(){
    pagereference newPage;
    string color;
    
     if(qliobj.Color_Name_Code__c == null) {
     if(qliobj.Color_Vendor__c=='Behr' || qliobj.Color_Vendor__c=='Benjamin Moore' || qliobj.Color_Vendor__c=='Comex' || qliobj.Color_Vendor__c=='Dunn-Edwards' || qliobj.Color_Vendor__c=='Glidden' || qliobj.Color_Vendor__c=='ICI' || qliobj.Color_Vendor__c=='Kelly Moore' || qliobj.Color_Vendor__c=='Kilz' || qliobj.Color_Vendor__c=='PPG' || qliobj.Color_Vendor__c=='Sherwin Williams' || qliobj.Color_Vendor__c=='Vista'){
        Apexpages.addMessage(new ApexPages.Message(Apexpages.Severity.ERROR,'Color Name/Code is mandatory if the color is not: Color Formula or No Tint'));
        return null;
    }
    }
    if(qliobj.Color_Vendor__c=='Color Formula'){
    //1st colorant
    if(qliobj.Colorant__c!=null){
     color =qliobj.Colorant__c;
    if(qliobj.OZ_1__c!=null){
    color = color +'-'+qliobj.OZ_1__c;
    
    }
    else
    {
    color =color +'-'+qliobj.X384ths_1__c;
    
    }
    if(qliobj.OZ_1__c!=null && qliobj.X384ths_1__c!=null )
    {
    color =color +'Y'+qliobj.X384ths_1__c;
    
    }
    }
    qliobj.Color_Name_Code1__c=color;
    
   //2nd colorant 
   if(qliobj.Colorant1__c!=null){
    color=color+';'+' '+qliobj.Colorant1__c;
    
     if(qliobj.OZ_2__c!=null){
    color = color +'-'+qliobj.OZ_2__c;
    
    }
    else
    {
    if(qliobj.X384ths_2__c!=null){
    color =color +'-'+qliobj.X384ths_2__c;
    }
    }
    if(qliobj.OZ_2__c!=null && qliobj.X384ths_2__c!=null )
    {
    color =color +'Y'+qliobj.X384ths_2__c;
    
    }
    }
    qliobj.Color_Name_Code1__c=color;
   
    
    //3rd colorant
    if(qliobj.Colorant2__c!=null){
     color=color+';'+' '+qliobj.Colorant2__c;
    
     if(qliobj.OZ_3__c!=null){
    color = color +'-'+qliobj.OZ_3__c;
    
    }
    else
    {
    if(qliobj.X384ths_3__c!=null){
    color =color +'-'+qliobj.X384ths_3__c;
    }
    }
    if(qliobj.OZ_3__c!=null && qliobj.X384ths_3__c!=null )
    {
    color =color +'Y'+qliobj.X384ths_3__c;
    
    }
    }
    qliobj.Color_Name_Code1__c=color;
    
    //4th colorant
    if(qliobj.Colorant3__c!=null){
    color=color+';'+' '+qliobj.Colorant3__c;
    
     if(qliobj.OZ_4__c!=null){
    color = color +'-'+qliobj.OZ_4__c;
    
    }
    else
    {
    if(qliobj.X384ths_4__c!=null){
    color =color +'-'+qliobj.X384ths_4__c;
    }
    
    }
    if(qliobj.OZ_4__c!=null && qliobj.X384ths_4__c!=null )
    {
    color =color +'Y'+qliobj.X384ths_4__c;
    
    }
    }
    qliobj.Color_Name_Code1__c=color;
    
    //5th colorant
    if(qliobj.Colorant4__c!=null){
     color=color+';'+' '+qliobj.Colorant4__c;
    
     if(qliobj.OZ_5__c!=null){
    color = color +'-'+qliobj.OZ_5__c;
    
    }
    else
    {
    if(qliobj.X384ths_5__c!=null){
    color =color +'-'+qliobj.X384ths_5__c;
    }
    }
    if(qliobj.OZ_5__c!=null && qliobj.X384ths_5__c!=null )
    {
    color =color +'Y'+qliobj.X384ths_5__c;
    
    }
    }
    
    qliobj.Color_Name_Code1__c=color;
    }
    else
    {
    
    qliobj.Color_Name_Code1__c=qliobj.Color_Name_Code__c;
   
    }
    
    update qliobj ;
    newPage = new PageReference(ApexPages.currentPage().getParameters().get('retURL'));
    return newPage;
    
    }
    
    /*public pagereference save(){
    pagereference newPage;
    update qliobj ;
    newPage = new PageReference(ApexPages.currentPage().getParameters().get('retURL'));
    return newPage;
    
    }*/

}