src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Converted_to_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted to Order</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Quote</fullName>
        <active>true</active>
        <label>Quote</label>
    </recordTypes>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Base__c</fullName>
        <formula>Product2.Base__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Base</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Name_Code1__c</fullName>
        <label>Color Name/Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Name_Code__c</fullName>
        <label>Color Name/Code</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Color_Vendor__c</fullName>
        <label>Color Vendor</label>
        <picklist>
            <picklistValues>
                <fullName>Behr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benjamin Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dunn-Edwards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kelly Moore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Tint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherwin Williams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vista</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant1__c</fullName>
        <label>Colorant 2</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant2__c</fullName>
        <label>Colorant 3</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant3__c</fullName>
        <label>Colorant 4</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant4__c</fullName>
        <label>Colorant 5</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colorant__c</fullName>
        <label>Colorant 1</label>
        <picklist>
            <picklistValues>
                <fullName>AXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VUL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OZ_1__c</fullName>
        <label>OZ 1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_2__c</fullName>
        <label>OZ 2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_3__c</fullName>
        <label>OZ 3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_4__c</fullName>
        <label>OZ 4</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OZ_5__c</fullName>
        <label>OZ 5</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sheen__c</fullName>
        <formula>TEXT(Product2.Sheen__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sheen</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <formula>Product2.Size__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Size</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use__c</fullName>
        <formula>TEXT(Product2.Use__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Use</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <formula>Product2.Vendor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X384ths_1__c</fullName>
        <label>384ths 1</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_2__c</fullName>
        <label>384ths 2</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_3__c</fullName>
        <label>384ths 3</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_4__c</fullName>
        <label>384ths 4</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X384ths_5__c</fullName>
        <label>384ths 5</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/Behr_CustomQuoteLineItemController.cls
public class Behr_CustomQuoteLineItemController {
  public string product{get;set;}
  //public boolean colorNoint{get;set;}
  //public boolean colorformula{get;set;}
 public QuoteLineitem qliobj{get;set;}
 public String colorvendor{get; set;}
 public Boolean flag{get;set;}
 public boolean quoteDisplay{get;set;}
 public boolean orderDisplay{get;set;}
    public Behr_CustomQuoteLineItemController(ApexPages.StandardController controller) {
     flag=false;
        qliobj =[select quoteId,ListPrice,Quantity,Color_Vendor__c,Color_Name_Code1__c,Color_Name_Code__c,Use__c, Sheen__c, Base__c, Vendor__c, Size__c,
                 X384ths_5__c, X384ths_4__c, X384ths_3__c, X384ths_2__c, X384ths_1__c, OZ_5__c, OZ_4__c, OZ_3__c, OZ_2__c, 
                 OZ_1__c, Colorant__c,Colorant1__c,Colorant2__c,Colorant3__c,Colorant4__c, Unitprice, Discount from QuoteLineItem 
                 where id=:ApexPages.currentPage().getParameters().get('id')];
                 
         RecordType rt = [select id, name 
                     from Recordtype 
                     where sobjectType ='Quote' and name = 'Quote'];
          Quote q=[select id,recordtypeid,Converted_to_Order__c from Quote where id=:qliobj .QuoteId];          
                 
                  if(q.recordtypeid==rt.id){
                  quoteDisplay=true;
                    
              }
              else     {
                   orderDisplay=true;
                   if(qliobj.Color_Vendor__c=='Color Formula'){
                    flag =true;
                    //colorformula=true;
                    }
              
              
              }                 
               
    
    
                 
                 
                 
    }
     public void onchange1(){
        
        if(qliobj.Color_Vendor__c=='Color Formula'){
        flag =true;
        
        //colorformula=true;
        }
        else{
        //colorNoint=true;
        }
        system.debug('onchangeeeeeeeeeeeee'+flag);
       // return null;
        }
    
  
    
}